### ISSUE TITLE
Site Addition request

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#114]
Hello Mate..Thank you for your great job on Videodevil. This is the only add-on where dedicated Indian count can be found. May I draw your attention on two things please. 1) if possible, kindly add clipsage.com..this site has good and exclusive Indian content. 2) site vmasala and indiangilma not working from a long time now. Kindly check at your end

**Comment by Gujal00** [comment]
Both things addressed in https://github.com/xbmc-adult/xbmc-adult/pull/115, Needs Dquaid's review and approval
