### ISSUE TITLE
Tukif Error when trying to start a video

### ISSUE THREAD

**Issue by Grossdm** [xbmc-adult/xbmc-adult#117]
Everything about Tukif appears normal, but whenever a video is selected it fails to run.

There is a Kodi notification message "Sorry! Unable to find the video"

(I just noticed that I might need to specify that this issue is for **plugin.video.videodevil**)

Thanks to all of the devs and contributors on this project!

**Comment by Gujal00** [comment]
Fix done in https://github.com/xbmc-adult/xbmc-adult/pull/120
