### ISSUE TITLE
Pornhub in VideoDevil not working since March 2 update

### ISSUE THREAD

**Issue by JNightshade** [xbmc-adult/xbmc-adult#122]
Sorry if I'm using wrong protocol, I'm new to Github AND not a programmer. I do enjoy VideoDevil, and particularly PornHub, but since the update to 1.7.181  it will read directories and videos complete with metadata, but when you try to load it says, "Sorry Unable to find the Video" I first encountered this on the afternoon of March 3. It was working the previous evening. ( ok I like porn on in the BG, it's comforting :) I tried installing 1.7.177 but whatever else was changed is beyond my capabilities unless I can recover an older backup. I appreciate the work on the addon, and look forward to a speedy recovery.
Thanks
I

**Comment by mrdougquaid** [comment]
Fixed

**Comment by JNightshade** [comment]
And tested.
Thanks. That’s great.
