### ISSUE TITLE
Site Addition Request javhihi.com

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#124]
Hi, can you please add javhihi.com. This is one of the best japanese porn site with huge selection in HD and all uncensored. Thank You.

**Comment by Gujal00** [comment]
Added in version 1.7.186

**Comment by imurreflection** [comment]
Thank you so much mate. Have a nice day !

**Comment by Gujal00** [comment]
If you are okay with the release, Can you close the issue please.
