### ISSUE TITLE
"Next Page" not working after search

### ISSUE THREAD

**Issue by koldomon** [xbmc-adult/xbmc-adult#127]
I see 1/3 Pages. When I click "next page" i stay on the same page. happens in ph, yp

**Comment by mrdougquaid** [comment]
Which plugin ? 
Which site ?

**Comment by koldomon** [comment]
Sorry, I forget to give you the information

The Plugin is "plugin.video.videodevil". I use in in Kodi-MC. (both are up-to-date) It happens on Pornhub, Youporn and as I see, there is a max. of 28 Results on "Search". Maybe "behavior by design"?
