### ISSUE TITLE
Site addition request jav789.com

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#132]
Hi, first thank you for this great add-on. May I request you to check the possibility for the addition of the site jav789.com. This is a good site with mostly uncensored japanese porn.

**Comment by Gujal00** [comment]
Seems to be a clone site of javhihi as all the final videos are being pulled from javhihi
As javhihi is already available in Videodevil, is adding this site worthwhile?

**Comment by imurreflection** [comment]
I thought so too but this is not the case. If you see, you will observe
that all videos from javhihi is from javhd and all uncensored but jav789
shows content from all uncensored studios including heyzo,Caribbean, Tokyo
hot, 10musume etc and you will not find a single video from these studios
in Javhihi. This will definitely b worthy addition mate

**Comment by imurreflection** [comment]
One example would be search for "kozue" where Javhihi returns no result but jav789 returns 2 results.  Jav789, javbuzz and letfap.com seems to be their sister sites but all shows different content and all are excellent sites.  Letfap.com is absolutely outstanding western porn site with amazing content

**Comment by Gujal00** [comment]
yep, noticed letfap was different content. Okay will take a crack at these sites

**Comment by imurreflection** [comment]
Thank you so much mate. I am sure these additions will make our add-on the best of all.

**Comment by Gujal00** [comment]
Jav789, javbuzz and letfap.com added in #141

**Comment by imurreflection** [comment]
Oh my god..this is a mega addition. Thank you so much and I apologize for incorrect issue naming on my other issue on E-Porner but let me tell you Gujal00, you are the best. Thanks again
