### ISSUE TITLE
Site addition request

### ISSUE THREAD

**Issue by trex78** [xbmc-adult/xbmc-adult#135]
Hi, i've got some premium sites that would be nice it they could be added in the addon:
https://xmoviesforyou.com
https://palimas.tv
https://bitporno.com
https://xfreehd.com
https://yespornplease.com
https://biqle.ru
https://hqporner.com
https://yourporn.sexy

Thx !

**Comment by ruegnueg** [comment]
bitporno is on uwc included, also yourporn.sexy but yourporn.sexy stopped working in uwcseems

**Comment by ruegnueg** [comment]
could javhihi be fixed? a working yourporn.sexy would be awesome

**Comment by Gujal00** [comment]
@ruegnueg What is wrong with javhihi other than sorting which is fixed in #139

**Comment by ruegnueg** [comment]
@Gujal00 yeah it runs agan, was maybe just an issue on the site itself.

**Comment by ruegnueg** [comment]
So, any plans for adding yourporn.sexy?

**Comment by Gujal00** [comment]
yourporn.sexy uses other embedders such as openload, so not a fit for videodevil
A basic guideline for videodevil is that the site host their videos themselves and not use embeds from other sites.

**Comment by Gujal00** [comment]
>
> Hi, i've got some premium sites that would be nice it they could be added in the addon:
> https://xmoviesforyou.com

All the videos are hosted at other embedders. Not possible to do in Videodevil
> https://palimas.tv

Does not host the videos and relies on other embedders. Not suitable
> https://bitporno.com

Already present in VideoDevil
> https://xfreehd.com

Complex catcher for videodevil. May be possible
> https://yespornplease.com

too much javascript for the catcher to handle. Not suitable
> https://biqle.ru

Site is defunct
> https://hqporner.com

Does not host the videos and relies on other embedders. Not suitable
> https://yourporn.sexy

Does not host the videos and relies on other embedders. Not suitable

Please close the issue as there is one site in that list that may be possible. All others can't be done in VideoDevil.
