### ISSUE TITLE
Many sites down

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#137]
Hey mate, something is not correct. Many sites are not working. Sexu, vporn,spankwire,pornomovies,porn.com,indianpornvideos,indiangilma,fappy,desixnxx and ah-me are not working। Please take a look. However, if you are not developing the add-on any more then kindly ignore.

**Comment by mrdougquaid** [comment]
ah-me is working fine
deleted faapy
Desixnxx is still broken
deleted indiangilma
indianpornvideos still broken

**Comment by mrdougquaid** [comment]
pornomovies works but kodi doesn't have the correct plugins to play the videos

**Comment by Gujal00** [comment]
Any reason why faapy was removed? The site seems fine
I have done a PR for some other fixes.

**Comment by mrdougquaid** [comment]
faapy was broken when I checked
