### ISSUE TITLE
Pornhub Titles and Thumbnails Mismatch 

### ISSUE THREAD

**Issue by JNightshade** [xbmc-adult/xbmc-adult#138]
Hi, the titles and the thumbnails have been mismatched for about a week I think. Sometimes they are off by one line, sometimes more. Wasn’t sure if it was VideoDevil or Pornhub’s issue. 
Thanks.

**Comment by mrdougquaid** [comment]
Fixed

**Comment by JNightshade** [comment]
That’s great thanks.
