### ISSUE TITLE
Eporner No "Next" Tab 

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#140]
Hi, thank you for immediate action on my last reported issues. Please note that the site Eporner doesn't have any 'Next' tab available which limits the site content completely. Even in search, it is limited to one page. Kindly fix it as this is one of the best site. Thank You

**Comment by Gujal00** [comment]
Please change title to
[Videodevil] Site - issue/request which makes it easy to look at issues
So yours should be
[Videodevil] Eporner - No next tab

**Comment by Gujal00** [comment]
Fixed in #141
