### ISSUE TITLE
Site issues- Jav789,Javbuzz and letfap.com

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#142]
Hi, first, thanks a lot for adding this site. However, when you click on any link, first the playback circle gets stuck for a long time and when it resumes circling, three things happen 1) Playback completely stops no matter if you select any quality 2) Playback starts but then gets stuck immediately with no video. Any attempt to do rewind/fast forward results in closure of playback and takes you to previous video list page. 3) If you manually stop the playback, it takes huge time to get back to previous page.

Previously added site Javhihi has no issues with playback or playback time.   Kindly have a look and have a great day

**Comment by Gujal00** [comment]
Is it working for you on the website without issue?

**Comment by imurreflection** [comment]
Yes mate, it's working just fine without any playback issue/s.

**Comment by mrdougquaid** [comment]
Takes a while to start. Sometimes fails when fast forwarding but if you just watch it is fine

**Comment by imurreflection** [comment]
No mate, I tried watching but after 2 minutes and 4 seconds, it just
stopped. No buffering, only black screen and then it stops completely. I
was watching a video on Jav789.com. please check it yourself. Then I tried
other two sites also but same result.

**Comment by Gujal00** [comment]
The start times are identical between all 4 sites on Kodi 18. However the encodes seem to be different as on javhihi they are seekable but on the others not seekable directly, but you can pause the video and then seek the point you need to.
Overall all 4 sites are struggling recently to stream smoothly, may be it is just load on those sites. Can't do anything about it on the Addon

**Comment by imurreflection** [comment]
On normal PC, these sites works without any issue or lag and you can even do fast forward and or rewind. On our add-on Javhihi doesn't struggle at all. Also, there is not even a single video playable on Javbuz.com. However, as you are the developer, you know the best. May I request you to keep checking add-on periodically for any anomalies with these sites mate.

**Comment by imurreflection** [comment]
Hi, these 4 sites are not working again. Sorry unable to find message on every video. Day before yesterday all these sites were working absolutely fine with no issues with fast forwarding or anything at all. Then these websites went on maintenance and I found that they have changed their video host to 'Rapid Video" ..if this could help. Just to let you know that these sites are working fine on mobile or PC browser. Kindly fix them. Thanks in advance

**Comment by ruegnueg** [comment]
In videodevil 1.8.3 all jav sites are gone. in 1.7.9 none of them worked 😭

**Comment by Gujal00** [comment]
These sites cant be done in VideoDevil anymore as the final url resolution has become complex for the catcher function. Possibly need to be done as a dedicated addon

**Comment by imurreflection** [comment]
I agree mate. Let's remove them and if possible add some sites like
hclips.com,porntrex.com and daftsex. They are here from a long time and
they have good content. They are also present in ultimate white cream but
have been dead from quite some time and issue cannot be rectified as
developer abandoned the add-on months back. Thank you for all your hardwork
to keep this add-on alive.

**Comment by Gujal00** [comment]
@imurreflection Can you close this issue please

**Comment by imurreflection** [comment]
Can you please advise how can I close it. I don't see any option to do so

**Comment by imurreflection** [comment]
Got it...closing it now. Thanks for all your help on this one bro
