### ISSUE TITLE
Sonyliv add-on not working

### ISSUE THREAD

**Issue by plikmuny** [xbmc-adult/xbmc-adult#144]
Hi gujal, I just want to tell you that the sonyliv add-on in deccan delight not working.
Can you check it pls ?

**Comment by Gujal00** [comment]
Why is this being reported here. This repo has got nothing to do with the addon you are mentioning

**Comment by plikmuny** [comment]
Hi, i saw this addon in your latest Repo. I thought you have incorporated
it into DeccanDelight.
Why did i see this Addon in your Repo, that i dont know. But i can see it.
Have you got abything to do with this ? i dont know that also.

Thinking that ist freely available and in your Repo, i assumed that ist you
who incorporated it.

I just told you that ist not working. Could you fix it ? it would be more
helpful if you could do so.

Thanks in advance. nothing Offensive.

As Always great effort.... Keep it up.

**Comment by mrdougquaid** [comment]
Wrong repo. Please report to the correct repo owner
