### ISSUE TITLE
Site Addition Request- rartube.com

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#151]
Hello my friend, first let me congratulate you for being only one Kodi porn add-on constantly being updated and ofcourse there is no competition. As you know some hindi/ indian porn content has been removed and some other sites ceased to operate,May I request you to add rartube.com which has authentic and rare indian/Bangla content.

Keep up the great job mate!!!

**Comment by Gujal00** [comment]
PR #154 raised to add rartube.com and sister site nostami.com
