### ISSUE TITLE
Site Issue: Eporner

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#156]
Hello Mate, please be advised that Eporner site is not working, nothing happens when you click the link. On mobile and PC browser, the site is working fine. Kindly fix it

**Comment by nabilbendafi** [comment]
Nothing wrong on PC :
- [x] Categories
- [x] Search 
- [x] Sorting
- [x] Video link : low, standard, HD

Tested version 1.7.202

**Comment by nabilbendafi** [comment]
After further investigation it seems that site reports :

> You have downloaded more than 30 videos today.
>
> Please try again tomorrow or register for free to download up to 100 videos per day.

That might explain why nothing happens when you click. @imurreflection can you confirm ?

**Comment by imurreflection** [comment]
Hi, thanks for replying. The issue persists as I just checked.  The version is 1.7.202. Also, I have never watched 30 videos in a day and I don't download anything since streaming is better as I have 100mbps unlimited speed. Also, just checked that xvideos is also down. These sites were working absolutely fine earlier. Also, I never said that there were any issues on PC or even mobile browser. Kindly let me know if you need more information.

**Comment by mrdougquaid** [comment]
Eporner works fine for me too. 
Try not accessing the site for a few days and lets us know if it starts working.

**Comment by imurreflection** [comment]
This is strange..This never happened with this site earlier.  This cannot be due to geo restrictions as the same site on same network works fine on mobile..the site was working absolutely fine before I report it. Can you advise the version number it's working for you on.

**Comment by imurreflection** [comment]
Ah..I sincerely apologize for reporting this issue before confirming at my end. I checked again and found that the site is blocked by ISP and my VPN using Singapore server unblocked it. Please close this issue
