### ISSUE TITLE
No thumbnail preview images on Porntrex

### ISSUE THREAD

**Issue by stemei2013** [xbmc-adult/xbmc-adult#166]
VideoDevil Plugin:
When entering Porntrex there are no thumbnail preview images of the videos available

![grafik](https://user-images.githubusercontent.com/44786006/48022917-b1148700-e13c-11e8-80de-f0e25e2fd111.png)

**Comment by bj136** [comment]
To fix the thumbnail issue unzip the attached file and replace the two files with the existing files in ...plugin.video.videodevil\resources\  folder.... I not sure about the next page issue which only occurs in category folder. Ill let the smarter people figure that out..  

btw.. I am very new to github and I am sure there is a way contribute in a more efficient way....

**Comment by Gujal00** [comment]
Fixed in #169
