### ISSUE TITLE
Plusone8 - No Next Page in Search

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#184]
Hi Nabilbendafi Bro, Thank you for this great site. However, please note that there is no Next tab available during any keyword search. Seems to be similar issue like Porntrex. Also, quality selection option is not available. Kindly fix it. Thank you again for this high quality site.

**Comment by nabilbendafi** [comment]
@imurreflection:
- The quality selection option is not available at all on the site, so basically not much can be done about it. 
- On the other hand, _Next_ tab should be doable. I'll try to add it soon.

**Comment by nabilbendafi** [comment]
Oh! Actually, the _Next_ tab **is** working. The problem is that one the website, the _Exclusive videos_ are displayed on each pages (right side), thus displayed on _Videodevil_.
It looks like nothing much can be done about it.
