### ISSUE TITLE
Add hentaiheaven

### ISSUE THREAD

**Issue by wintuxx** [xbmc-adult/xbmc-adult#190]
There is at moment no good addon that supports this site. Okay, there is xxxoxdus, but I don't like this addon, because the pin request

**Comment by Gujal00** [comment]
Catcher is straightforward but the pagination is a ajax call, hard to code for Videodevil

**Comment by wintuxx** [comment]
Mayby this could help
https://github.com/wintuxx/plugin.video.uwc/blob/master/resources/lib/sites/hentaihaven.py
i have found this last verson of uwc and uploaded to my git account.
i have used uwc to watched the videos on hentaiheaven,but one day the videos wouldn't start.
The Download of the videos still works.

**Comment by wintuxx** [comment]
i am a starter with pyton and i could not fix the not start issue.

**Comment by Gujal00** [comment]
@wintuxx there is no python code in videodevil site plugin codes. Pagination can't be done for this site using videodevil methods

**Comment by Gujal00** [comment]
@mrdougquaid This issue can be closed as HentaiHaven have closed the website forever with a Goodbye Message
