### ISSUE TITLE
ADD SITES 

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#192]
GOOD WORK DONE BY ADDING HD CONTENT SITES LIKE PORNTREX AND HQPORNER 
PLEASE ADD 
PORNFLIP.COM AND DAFTSEX.COM
REMOVE PLUSONE8 AS IT DOES NOT HAVE ENOUGH CONTENT

**Comment by mrdougquaid** [comment]
Do not use all caps on the internet because it is akin to shouting. All caps is considered shouting on the internet. Shouting is not polite. Therefore, it is bad netiquette to use all caps on the internet because shouting is not polite.

**Comment by Sameer888** [comment]
Pls dont be so harsh and rude why will i shout on you i am very thankfull
for your work on this addon .Sorry if yu felt bad for using capital letters
