### ISSUE TITLE
Add spank bang 

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#194]
Kindly see if there is a possibility of adding extremely high quality site Spankbang.com.  This site has huge content with various categories and addition of this site will make our already great add-on much better.

I am really thankful to you for accommodating my requests in recent past and extending your expertise. I would like to assure you that this will be my last request for any site addition. Thank you very much for your great work and have a blissful day everyday.

**Comment by Gujal00** [comment]
Added in #200

**Comment by imurreflection** [comment]
Thank you so much mate. Have a nice day!

**Comment by imurreflection** [comment]
Hi mrdougquaid, may I request you to release the updated version please
