### ISSUE TITLE
Sites not working

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#195]
Please note that Bitporno and HQporner sites are not working. Kindly have a look . Update 11th December. Now Porntrex is not working either.

**Comment by Gujal00** [comment]
Please check if bitporno is working on the browser. Looks like it is blocked by some ISPs. It is working fine for me.
nabil did the other two sites, I think he will get to them

**Comment by imurreflection** [comment]
mrdougquaid, may I request you to release the update please for the above fixes

**Comment by imurreflection** [comment]
Hey mate, ignore this request. I manually updated the configuration files and now it's working fine. Thanks to you and nabilbendafi. Have a nice day both
