### ISSUE TITLE
Site Issue

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#202]
Please its a request to  skip private videos in porntrex  and    There is issue with Bitporno in specific pornstar search please resolve it 
Thank you

**Comment by Gujal00** [comment]
Can you detail a bit more on what happens with bitporno search?

**Comment by Sameer888** [comment]
When searching a particular pornstar its giving the results with same other names and this problem was not there in previous versions

eg: Searching Mandy muse giving results with Mandy Moore , Mandy dee and other pornstars with name Mandy its not giving results with specific mandy muse 

Please resolve it thank you

**Comment by Gujal00** [comment]
That is how the bitporno site search function works. You can verify by visiting the bitporno site in a web browser and search mandy muse, it will return exactly what you see inside VideoDevil. The addon behaves exactly as the site as expected. Unfortunately nothing can be done on the addon to fix this problem

**Comment by Sameer888** [comment]
Ok sir than what about porntrex private videos it should be skipped because some video are not playable  Please its a request to add daftsex also
It has tonnes of Hd content , 
Thank you

**Comment by Gujal00** [comment]
I have mentioned this before, daftsex can't be done in Videodevil due to the way pagination is done on that site
