### ISSUE TITLE
Porntrex not working

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#208]
Hello Friends, Porntrex is not working. Kindly have a look. It appears that whenever we try to implement ' Skip Private Video' feature, it breaks the code. That feature is not required as we just have to ignore that video.

**Comment by imurreflection** [comment]
Bro, please understand..UWC coding is different than Video Devil and that's why these great helping people were not able to add your much sought daftsex . please its not in their hand. If you keep requesting incompatible changes, the code will break and we will not be able to see anything for a long time. Hope you understand mate

**Comment by Sameer888** [comment]
Ok bro i had a doubt so i asked but no worries we can go with unskipped videos in porntrex only matters it should work well

**Comment by imurreflection** [comment]
Hi Gujal00 bro, may I request you to kindly look at this and please don't implement skip private video change any more.

**Comment by Gujal00** [comment]
The site has gone full HTML5+CSS+AJAX since last week, so the pagination is split into 3 parameters. In videodevil it is only possible to handle 2 paramters (url+url.append). It is beyond me. May be @nabilbendafi who did the site code for porntrex has some other idea

**Comment by imurreflection** [comment]
Ah..this is an irony ..this was a really good site. Thank you for your efforts mate. May be @nabilbendafi can pull up something. Have a nice day.

**Comment by imurreflection** [comment]
Thank you mate.
