### ISSUE TITLE
Tutorial / Guidding Lines to add new sites to VideoDevil?

### ISSUE THREAD

**Issue by Mafarricos** [xbmc-adult/xbmc-adult#21]
Is there any tutorial to add new sites? Is only needed to add the site to catcher.list and create a .cfg file, isn't needed to add new code to .py?

What kind of things are to be taken care off? And have to be in consideration.

**Comment by mrdougquaid** [comment]
No tutorial, maybe just look in the git history
Don't add low quality sites or sites that just pull videos from other sites

**Comment by Mafarricos** [comment]
In terms of resolving the videos, if is a site with direct link to video, will work right away with the correct regex, or for new sites is necessary to change the .py? for what I understand the .py code is generic and are the config files that make the different sites to work, right?

Is only that I don't understand 100%, if with new sites is necessary to change code in .py

**Comment by mrdougquaid** [comment]
Yes videodevil.py is generic and does not need to be changed for new sites.

Look at https://github.com/xbmc-adult/xbmc-adult/commit/f3fbdb73de83a98f41348b32e96f6b81fd507890 for an example of adding a new site
