### ISSUE TITLE
Please add these sites

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#216]
Paradisehill.cc
Tubepornclassic
Full length video content

**Comment by Gujal00** [comment]
So you keep asking for sites one by one from UWC to be included in videodevil. why not request those sites to be fixed in uwc on their forum? It would be much easier to fix there than to try and implement in Videodevil
```https://github.com/tvaddonsco/tva-adult-repo```

**Comment by Sameer888** [comment]
Uwc is not maintained by its developer and Videodevil is maintained by you all guys with good support so that is why want and addition of these sites if someone is undertaking maintainence of uwc then its good for all but i think this cant happen
