### ISSUE TITLE
Gujal00 Bro please help

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#217]
Hi Mate, please assist and advise how can I manually update the add-on to reflect new changes. I can manually modify catcher, sites list, settings etc but it will be updated only for existing sites and not for newly added sites. mrdougquad is not active from 2nd January and it appears that he must be busy. If you teach me, I can manually update the changes myself rather than waiting for him to release new update. Please help.

**Comment by Sameer888** [comment]
Hi imurreflection Bro i think first Porntrex should be fixed and then only the version should be released
Porntrex is the best site in videodevil if it is not fix by Gujal00 than Nabilbendafi Bro can fix it

**Comment by imurreflection** [comment]
Sameer bro ...understand, these people are developers and they know what can be done and what can't. If Gujal00 bro says that he can't do it then I really doubt anybody else can because I know his expertise. Gujal00 bro, please assist me with my query.

**Comment by Sameer888** [comment]
Are yu sanjeev on telegram

**Comment by imurreflection** [comment]
Yes..please delete your post

**Comment by Gujal00** [comment]
Every pull-request on GH can be downloaded as a mail-patch, just by appending ".patch" to the pr URL.

E.g., from:
`https://github.com/xbmc-adult/xbmc-adult/pull/206`

To:
`https://github.com/xbmc-adult/xbmc-adult/pull/206.patch`

This will generate a mail-formatted patch file, that is a little different from an usual patch file: It has e-mail metadata.

After downloaded, apply the result patch using:
`git am 206.patch`

**Comment by imurreflection** [comment]
Bro, some more help please on last step. I have downloaded the text file as patch file in mail format as you said. Can you please help in little less technical terms on how do I apply the result patch.

**Comment by imurreflection** [comment]
##>>awIXo1J192jTu7JjOhttqf+gPnLnTRoZQkmdqcMLWzYw42+a4Cb/tsw0wWajzdRTNUSR+jqBOODaUmCtlJpZ7eq/YPzwUvf/HT4wLVIUYIi0Fe1PndyWfai7PDJ9Qg/uxvKiOzPZ0uzU6iuHuBDImg7uVjELsC3Pm5AFnwrro+U=##>>vovalink://web?url=freebies&immersive=1&immersiveTitleColor=#ec2c2c##>>{"origin":"freebies","vvlink_id":"4677651"}

**Comment by Gujal00** [comment]
Get Git for windows from `https://gitforwindows.org/` and install it
Then do a
`git clone https://github.com/xbmc-adult/xbmc-adult.git`
Then go into the xbmc-adult directory and run
`git am 206.patch`
This will patch the local xbmc-adult source.
Do for each of the pull requests that you want to integrate. Once done copy the modified files to your kodi videodevil install directory.
For more details read the git manual
`https://git-scm.com/doc`

**Comment by imurreflection** [comment]
Thanks Bro.. last help please.. I downloaded Git for windows. Please clarify my doubts.
1) shall I save pull requests as text file on my PC?
2) Should I run git.gui. If yes, should I point the zip clone for xbmc adult? If I do so, it says "No Repositories Found".
3) in Git.ui where should I point my files to? 
4) I also downloaded get desktop and was able to clone xbmc adult but then not sure where to go from here.
Please help mate.

**Comment by imurreflection** [comment]
I did a lot of research and finally found how to apply the patch but getting error as:                                                                                                                                                                                                                                                                                                                                                                            Sanjeev@DESKTOP-0ROPPHC MINGW64 ~/xbmc-adult/plugin.video.videodevil (ghmaster)                                                                                                                 $ git am 209.patch                                                                                                                                                                              error: corrupt patch at line 86                                                                                                                                                                 hint: Use 'git am --show-current-patch' to see the failed patch                                                                                                                                 Applying: New site DesiVdo                                                                                                                                                                      Patch failed at 0001 New site DesiVdo                                                                                                                                                           When you have resolved this problem, run "git am --continue".                                                                                                                                   If you prefer to skip this patch, run "git am --skip" instead.                                                                                                                                  To restore the original branch and stop patching, run "git am --abort".                                                                                                                                                                                                                                                                                                                         Sanjeev@DESKTOP-0ROPPHC MINGW64 ~/xbmc-adult/plugin.video.videodevil (ghmaster\|A


Sanjeev@DESKTOP-0ROPPHC MINGW64 ~/xbmc-adult (ghmaster)
$ git am 210.patch
error: corrupt patch at line 120
hint: Use 'git am --show-current-patch' to see the failed patch
Applying: New site kissjav
Patch failed at 0001 New site kissjav
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

Sanjeev@DESKTOP-0ROPPHC MINGW64 ~/xbmc-adult (ghmaster|AM 1/1)

I dont know where I am going wrong. KIndly advise

**Comment by Gujal00** [comment]
do the following first
`git am --abort`
Then use this command instead
`git apply 210.patch`

**Comment by imurreflection** [comment]
I tried mate but getting this error

Sanjeev@DESKTOP-0ROPPHC MINGW64 ~/xbmc-adult (ghmaster|AM 1/1)
$ git am --abort

Sanjeev@DESKTOP-0ROPPHC MINGW64 ~/xbmc-adult (ghmaster)
$ git apply 210.patch
210.patch:20: trailing whitespace.
########################################################
210.patch:21: trailing whitespace.
# kissjav.com VideoPortal
210.patch:22: trailing whitespace.
########################################################
210.patch:23: trailing whitespace.
start=https://kissjav.com/videos/
210.patch:24: trailing whitespace.
catcher=simple-match
error: corrupt patch at line 126

**Comment by Gujal00** [comment]
Sorry, it is beyond me now as the commands work fine for me. Most probably the patch files that you downloaded was not saved correctly, Just wait for mrdougquaid to release the new version if you can;t get git patch working

**Comment by imurreflection** [comment]
Mate.. learning is always interesting.  I tell you what I am doing. under xbmc folder which is cloned, I am right clicking and clicking "git bash here" then I am using the commands.. is this correct procedure. Also, you copy the entire data from pull issue as 210 in text file then changing the extension to .patch.. is this correct too. May I request you to provide 210 as patch file here so that I can see if there is anything wrong.

**Comment by Gujal00** [comment]
That is correct, but it looks like you didnt abort the earlier git am using `git am --abort`.
Also I am not sure if you saved the patch files correctly as you are getting trailing whitespace messages.
You can start afresh by deleting the xbmc-adult directory and start from git clone. do not use git am and use git apply instead

**Comment by imurreflection** [comment]
Please provide me 210 as patch file to see what I am doing wrong. I deleted the directory and started it fresh still getting patch error as whitespace message.

**Comment by Gujal00** [comment]
Get the patches from [here](http://ge.tt/2CsfCwt2)
It works on my machine correctly as below
```
gujal@nowhere MINGW64 /d/Documents/GitHub/xbmc-adult (ghmaster)
$ git apply 210.patch

gujal@nowhere MINGW64 /d/Documents/GitHub/xbmc-adult (ghmaster)
$ git apply 209.patch

gujal@nowhere MINGW64 /d/Documents/GitHub/xbmc-adult (ghmaster)
$ git apply 213.patch

gujal@nowhere MINGW64 /d/Documents/GitHub/xbmc-adult (ghmaster)
$
```
Doesn't matter in which order you apply the patches.

**Comment by imurreflection** [comment]
Thank you so much sir. the patches worked flawlessly and I updated the addon. Now, please one last help. Let me know the complete procedure of creating the patches. What I did is opened the pull request in PC browser and append .patch and as there was no way to download it, i copied the entire text into note pad and saved the file in "all files" as a patch file example 210.patch and then copied the files to xbmc folder and right clicked it and select "Git Bash Here" and got those error because the patch file was incorrect. However, when I copied your patch files and applied the same procedure, I did not get any error. Please tell me exactly what you did which I didnt and thanks again sir for teaching me. I am attaching these two files for your reference. Please advise.
[Patches.zip](https://github.com/xbmc-adult/xbmc-adult/files/2762311/Patches.zip)

**Comment by imurreflection** [comment]
Never mind bro. I found it. I should have saved the webpage as patch file. I did that. Cloned the directory again and applied the patch and this time it worked perfectly. No Whitespace message. Thank you again for this great teaching sir. Have a Nice day.

**Comment by mrdougquaid** [comment]
Do not use this issue tracker things like this (i.e: teaching how to install/use git) this belongs in forums for git and kodi, not here.
