### ISSUE TITLE
Tranny.one

### ISSUE THREAD

**Issue by DragEleven** [xbmc-adult/xbmc-adult#220]
Hi, First time here. Sorry for my English. A lot of google translator. :-) I also like the shemales sites, after seeing ashemaletube.com.

Could add the https://www.tranny.one/ ,  no login required like some ashemaletube videos.

Thank You.

P.S: I´m a complete beginner  and I would like to learn . I already saw some regex videos, but less complicated. Is there any tutorial that explains step by step how to make sites like the one I want? Ths

**Comment by Gujal00** [comment]
There is no documentation available. Just study this pull request to understand how it is done

**Comment by DragEleven** [comment]
Thank you very much. It´s possible add section https://www.tranny.one/hd/ for maybe better quality videos?

**Comment by DragEleven** [comment]
Thank You very much.
