### ISSUE TITLE
VideoDevil: Categories are not working

### ISSUE THREAD

**Issue by wintuxx** [xbmc-adult/xbmc-adult#223]
Hello!

In xvideos section from VideoDevil is the kategory option not working.
It shows only "tags" nothing else.

**Comment by pedrocosta1970** [comment]
I Think this works.

File: xvideos.com.cfg

Categories block:

Where:
`item_infos=<li\s*class="dyn.+?btn-default"\s*href="([^"]+)">([^<]+)`

Substitution:
`item_infos=<a class="btn btn-default" href="(.+?)">(.+?)</a></li>`

**Comment by wintuxx** [comment]
issue still there
categories are not working :/
