### ISSUE TITLE
Hq Porner issue

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#226]
In Hqporner when searching a pornstar its showing less results comparing to site and some videos are showing error and also playing in 360p 

Eg : Searching Mia malkova on site its showing 78 videos comparing to addon results and some videos are not playable

**Comment by nabilbendafi** [comment]
Some videos won't play at all, due to some limitation of the videodevil plugin, too much redirection (cf. #189)

**Comment by Sameer888** [comment]
Nabilbendafi Bro in porntrex there is 4k section but the highest resolution playable is 1080p 
Is there any possibility of adding 4k resolution 

And this problem of skipping private video in porntrex is fixed permanently or not
