### ISSUE TITLE
erome.com and Hypnotube.com Help

### ISSUE THREAD

**Issue by DragEleven** [xbmc-adult/xbmc-adult#227]
I'm a beginner , trying to learn,  I'm trying to create a simple addon, some websites, no search,  categories, next page, etc ... just the first page, and I'm doing comparing with the code from other sites, like ashemaletube,etc here already made and seeing the source code of the page, but I have had some difficulty because I do not know what to put in certain fields.

**For example:**

I tried creating the addon for **https://www.erome.com/explore**

I added to settings.xml :
`<setting id="Erome" type="bool" label="Erome" default="true" />`

and sites.list:
```
########################################################
title=Erome
type=rss
genre=Erome
director=VideoDevil
icon=https://www.erome.com/img/logo-erome-horizontal.png?v=3
url=erome.com.cfg
########################################################
```

I created the regex and it seems to work on Kodi, but when I go to run the video it gives an error: <urlopen error [Errno 11004] getaddrinfo failed>

erome.com.cfg
```
########################################################
# Erome VideoPortal
########################################################
start=https://www.erome.com/explore
catcher=erome.com
########################################################
# Videos
########################################################
item_infos=<a href="([^"]+)".+?title">([^<]+).+?src="([^<]+)".+?user">([^<]+).+?>.+?</a>
item_order=url|title|icon|title.append
item_info_name=title.append
item_info_build= (%s)
item_info_name=type
item_info_build=video
item_url_build=https://www.erome.com%s
########################################################
```
catcher.list
```
########################################################
title=erome.com
target=source\s*src="([^"]+)
url=%s
extension=mp4
build=%s|User-Agent=iPad
quality=standard
########################################################
```

**Another example:**

I tried creating the addon for **https://hypnotube.com/videos/**

hypnotube.com.cfg
```
########################################################
# Hypnotube VideoPortal
########################################################
start=https://hypnotube.com/videos/
catcher=hypnotube.com
########################################################
# Videos
########################################################
item_infos=<a href="([^"]+)".+?src="([^"]+)".+?alt="([^"]+)".+?time">([:\d]+)</span>
item_order=url|icon|title|title.append
item_info_name=title.append
item_info_build= (%s)
item_info_name=type
item_info_build=video
item_url_build=https://hypnotube.com%s
########################################################
```

catcher.list

```
########################################################
title=hypnotube.com
target=source\s*src="([^"]+)
url=%s
extension=mp4
build=%s|User-Agent=iPad
quality=standard
########################################################
```

I do not know if the regex is completely correct, I think I do not know what to put in certain fields...especially in field "build" and I've seen in other codes other lines that I do not understand from where they came from like "header"...Referer...etc...

Could someone explain, please?

Thanks

**Comment by DragEleven** [comment]
I already managed to get the erome to work when are videos files :
erome.com.cfg
```
########################################################
# Erome VideoPortal
########################################################
start=https://www.erome.com/explore
catcher=erome.com
########################################################
# Videos
########################################################
item_infos=<a href="([^"]+)".+?title">([^<]+).+?src="([^<]+)".+?user">([^<]+).+?>.+?</a>
item_order=url|title|icon|title.append
item_info_name=title.append
item_info_build= (%s)
item_info_name=type
item_info_build=video
item_url_build=%s
########################################################
```
catcher.list

```
########################################################
title=erome.com
target=source\s*src="([^"]+)[^<]+res='480'
url=%s
extension=mp4
quality=standard
target=source\s*src="([^"]+)[^<]+res='1080'
url=%s
extension=mp4
quality=high
########################################################
```
I slowly realize how it is done...

Hypnotube also working:

hypno.com.cfg
```
########################################################
# Hypnotube VideoPortal
########################################################
start=https://hypnotube.com/videos/
catcher=hypnotube.com
########################################################
# Videos
########################################################
item_infos=inner-col">.+?href="([^"]+).+?src="([^"]+).+?alt="([^"]+).+?time">([:\d]+)</span>
item_order=url|icon|title|title.append
item_info_name=title.append
item_info_build= (%s)
item_info_name=type
item_info_build=video
item_url_build=%s
########################################################
```

catcher.list
```
########################################################
title=hypnotube.com
target=source\s*src="([^"]+)
url=%s
extension=mp4
quality=high
########################################################
```

**Comment by Gujal00** [comment]
yep, the item_url_build was the issue, as the url the regex was catching already had `href="https://www.erome.com/`. so no need to put it before %s

**Comment by DragEleven** [comment]
In hypnotube.com the thumbnail/icon of the videos does not appear...I tried to change some things but I can not find the solution...

I've seen that pornomovies.com (already exists) has the same problem.

Maybe because src is like this, with .mp4..i dont know:

```
src="https://cdn.hypnotube.com/thumbs/5/c/4/e/c/5c4ec621661b4-cumencouragement01.mp4/5c4ec621661b4-cumencouragement01.mp4-8.jpg"

src="https://thumbs.pornomovies.com/media/thumbs/4/9/6/5/3/4965355c50763309ab7.mp4/4965355c50763309ab7.mp4-3.jpg"
```
Can you help?

Thanks

**Comment by Gujal00** [comment]
may be the site has changed after you did the iteminfos for hypnotube as your regex is now failing with catastrophic backtracking.
This seems to work
`item_infos=href="(https://hypnotube.com/video/[^"]+).+?src="([^"]+).+?alt="([^"]*).+?time">([:\d]+)</span>`
still for images it may need some headers, will check and see if possible

PS: Pornomovies is a different issue, the regex is incorrect and needs fixing

**Comment by Gujal00** [comment]
@mrdougquaid 
This is the same issue that I raised a while ago on kodi forum about passing headers with icon_url. These icons need the Referer headers passed to Kodi ListItem for it to be displayed.
I have modified videodevil.py to support this by using `$HEADERS$` as a separator and it works correctly when used as below.
`item_info_name=icon`
`item_info_build=%s$HEADERS$Referer=https://hypnotube.com/`
I can submit a PR with changes to videodevil.py if this is acceptable. Please advise

**Comment by mrdougquaid** [comment]
That is fine. Send the PR

**Comment by DragEleven** [comment]
Works great with Hypnotube...

Thanks..
