### ISSUE TITLE
Can you add this site please-daftsex

### ISSUE THREAD

**Issue by ohmichael** [xbmc-adult/xbmc-adult#229]
Daftsex contains a lot of material and probably one of the best sites out there.

**Comment by Gujal00** [comment]
This site has been requested a few times before and cannot be implemented in Videodevil.
It is already available in uwc

**Comment by ohmichael** [comment]
It’s broken in uwc

**Comment by Gujal00** [comment]
so please raise a issue on tva-adult-repo git asking them to fix it. Daftsex cannot be implemented in Videodevil due to the use of HTML5+CSS+AJAX

**Comment by ohmichael** [comment]
Sorry just wanted to make sure-keep up the great work
