### ISSUE TITLE
Fixing issues not updates

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#233]
Fixing pornomovies by Gujal00 and 4k resolution of porntrex  by nabilbandafi   has not been updated in this release

**Comment by mrdougquaid** [comment]
Why did you open THREE issues about the same problem and then close them ? You are wasting my time because I have to read each and every one of them for nothing. 
I want you to stop opening new issues.

**Comment by Sameer888** [comment]
Mrdougquaid sorry for creating 3 issues for same problem i dont want to trouble you this happened by mistake acutally i wanted to say about porntrex 4k resolution than i thought there may be further issue with porntrex like it happened earlier so i closed it 

Please sorry again it wont happen again i will open issue only when its important 😔

**Comment by Sameer888** [comment]
Reply me Mrdougquaid 🤐
