### ISSUE TITLE
Fix Xvideos HD quality

### ISSUE THREAD

**Issue by DragEleven** [xbmc-adult/xbmc-adult#236]
Catcher only play with max quality 640x338
because:

SetVideoLow is not standard, but low
SetVideoHigh is not high, but standard
SetVideoHLS is missing for 720p/1080p

catcher.list:
```
########################################################
title=xvideos.com
target=setVideoUrlLow\('([^']+)
url=%s
extension=mp4
quality=standard
target=setVideoUrlHigh\('([^']+)
url=%s
extension=mp4
quality=high
########################################################
```

So, I think this will fix:

catcher.list
```
########################################################
title=xvideos.com
target=setVideoUrlLow\('([^']+)
url=%s
extension=mp4
quality=low
target=setVideoUrlHigh\('([^']+)
url=%s
extension=mp4
quality=standard
target=setVideoHLS\('([^']+)
url=%s
extension=mp4
quality=high
######################################################## 
```

**Comment by Gujal00** [comment]
HLS is just a multibitrate HLS Stream with both qualities, are you sure it is higher quality than the two we are pulling?
Yeah looks like xvideos are now serving high resolution streams through HLS only, that is a bummer as we can only play and cannot download HLS streams

**Comment by DragEleven** [comment]
For me it's okay ... I never do downloads ... I just want to see the best quality possible ...

**Comment by pedrocosta1970** [comment]
not yet pull request for HD Videos? If the solution of the @DragEleven works, please pull request, instead of the current  potato quality. Thanks.
