### ISSUE TITLE
Porntrex- no thumbnails

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#237]
Hi, there are no images, thumbnails in add-on.kindly fix it

**Comment by DragEleven** [comment]
@Gujal00

I think your solution solves the problem...:

```
item_info_name=icon
item_info_build=%s$HEADERS$Referer=https://www.porntrex.com
```

**Comment by imurreflection** [comment]
Friends, I don't want to trouble you with this. In other add-on, this is working fine. I am closing the issue now. Thank you
