### ISSUE TITLE
Gujal00 mate please assist

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#238]
Hi Bro, there is a site in our add-on eporner. The site works fine on WIFi on my mobile and my tablet. The site works fine on LAN also on my PC and android TV box through chrome browser. However, using the same local network, the site does not work on Kodi without VPN. I don't mind using VPN but it throttles down the speed from generally achieving 90 Mbps to 40
 
Can you please advise how to resolve this? Have a nice day

**Comment by Gujal00** [comment]
As @mrdougquaid had mentioned earlier, please do not use github for support issues.
Use the Support Thread at Kodi Forum
https://forum.kodi.tv/showthread.php?tid=188733
or
https://forum.kodi.tv/showthread.php?tid=58892

**Comment by imurreflection** [comment]
Since it was related to one of the site in the add-on,I thought its not a support issue. Anyways, the link provided by you doesn't have  any way to open new issue. Can you advise.

**Comment by mrdougquaid** [comment]
Not a problem with the addon.
You don't open issues in a forum, you just post your question

**Comment by imurreflection** [comment]
- You have all the rights to chose not to help but please see that my post was moved to violation under garbage..thanks for your help mate

https://forum.kodi.tv/showthread.php?tid=341128&pid=2825335#pid2825335

**Comment by Gujal00** [comment]
Why open a new thread on the forum? You post your question in one of threads I linked above and it will be answered by any of the forum users. As mrdougquaid said, there is no issue with the addon, it works fine for me too and is something specific to your install

**Comment by imurreflection** [comment]
But I never opened a new issue mate. I clicked on one of the thread only. Can you at least tell me what I should be looking for. All other sites work fine apart from xvideos which has the similar issue. Please help as there is no information available on internet else I would not have bothered you
