### ISSUE TITLE
Porntrex -No Images

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#240]
Hi, there are no thumbnail/images in Porntrex. Kindly fix it.

**Comment by DragEleven** [comment]
You closed the post with the solution. [Here](https://github.com/xbmc-adult/xbmc-adult/issues/237).

**Comment by imurreflection** [comment]
Hi, I closed the issue earlier because it was working in another add-on but then I realize that it should be fixed for our add-on also. Thank you gujal00 mate for fixing this.
