### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#242]
Hi, I have just found a site offering high quality full length Indian/ western content. Some of them are quite rare and unseen. Is it possible to get this site added on to our add-on? 
The site in question is 
https://www.thumbzilla.com

**Comment by Gujal00** [comment]
Looks like it can be done. Will take a stab at it

**Comment by imurreflection** [comment]
Thank you so much mate. Have a nice day

**Comment by Gujal00** [comment]
@imurreflection After a deeper look, it is just linking to videos in Pornhub, as we already have Pornhub in Videodevil, is it worthwhile having this site?

**Comment by imurreflection** [comment]
Yes my friend...even I thought so but after careful check, I observe that some videos are indeed new and unseen. Also, thanks to you, I have already used git bash to get the new update.

Sent from Mail for Windows 10
