### ISSUE TITLE
A new Indian porn site

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#257]
Hi Gujal bro..I just found an amazing  Desi site..ooodesi.com. Can you get this added or take a look at it please. If its a redirect then please ignore it.

**Comment by Gujal00** [comment]
The videos are not hosted by them and instead in hosters like openload.
Videodevil catcher can't handle such hosts as it only supports rudimentary regex.

**Comment by imurreflection** [comment]
Oh...I completely understand. Thank you. Closing the issue now.
