### ISSUE TITLE
Pornhd

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#262]
Not working. Nothing happens when you click a link

**Comment by Gujal00** [comment]
Don't know if this can be fixed. Needs cookie handling which currently I dont see any way to do it in catcher. may be @mrdougquaid can have a look at this

**Comment by mrdougquaid** [comment]
What sort of handling? 
You can do things like to set values in cookies. There are examples in the code.
header=Cookie|version=mobile

**Comment by Gujal00** [comment]
@mrdougquaid not setting a cookie, but use the cookie provided by the webpage and append it to the final play url. The page is sending two cookies (session id and csrf-token) and they have to passed with the play url

**Comment by mrdougquaid** [comment]
does it have to be in the URL? 
usually cookies are handled by the addon and stored in cookies.lwp

**Comment by Gujal00** [comment]
@mrdougquaid Yes the page opened by the catcher comes with cookies which need to be appended to the final url for it to play. If cookies are not present it opens a redirected html page instead of the stream

**Comment by imurreflection** [comment]
Hi mrdougquaid..I m not sure if its going to help but the site URL has been slightly changed to pornhdin.com
