### ISSUE TITLE
Please add newdesix

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#266]
Hi Gujal00 bro, there is a new desi site with amazing unseen content. newdesix.com. as vmasala.com has DNS registration issue and its unlikely the site will come back ,if you want you can remove it and add this site if you deems fit.

**Comment by Gujal00** [comment]
Looks like the site is malware laden
![Malware](https://i.imgur.com/tJ7s6BW.png)

**Comment by imurreflection** [comment]
Strange, I use it on my mobile and tablet and I don't see such messages. Can you please check again as this site has amazing content

**Comment by imurreflection** [comment]
https://drive.google.com/file/d/1FGf3DmQRT9AWZ8bYnw8QsmZtkfqcnZn1/view?usp=drivesdk

**Comment by imurreflection** [comment]
https://drive.google.com/file/d/1ZgMX4DpNoTJhagDvU-qU1s9vDca7WW1G/view?usp=drivesdk

**Comment by imurreflection** [comment]
Thank you much bro. The site is there in latest version and working fine. I m closing this request now. Thank you again to you and mrdougquaid
