### ISSUE TITLE
Site Not Working Celebsnude

### ISSUE THREAD

**Issue by Sameer888** [xbmc-adult/xbmc-adult#269]
Celebsnude, Clipage not working

**Comment by Gujal00** [comment]
Clipsage seems to be working fine, check in your web browser if you can access the site without any cloudflare intervention
Will take a look on celebsnude as it is broken

**Comment by Sameer888** [comment]
Clipsage is working fine
 Gujal00 Please fix the other sites which are broken as reffered by imureflection
