### ISSUE TITLE
Sexu.com- Broken Again

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#279]
Only spinning wheel while trying to play any video from categories and manual search. Moreover, it hangs kodi. Kindly fix

**Comment by Gujal00** [comment]
Working fine. If still issues, Uninstall and reinstall Videodevil 1.7.224

**Comment by imurreflection** [comment]
I don't know how this happened. First, I didn't get any .224 update and now when I forced update it..issues doesn't persist. Could this be because of Kodi Leia?

**Comment by imurreflection** [comment]
Thank you bro..closing the issue now
