### ISSUE TITLE
Doodhwali.com- Missing

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#281]
Just observed that the site doodhwaali.com is missing in the new updates. Please look into it

**Comment by Gujal00** [comment]
Lists and plays fine. Check if the site is enabled in videodevil settings

**Comment by imurreflection** [comment]
This is strange..all sites are enabled but this site is not there.. Till yesterday, it was there

**Comment by imurreflection** [comment]
.224 resolved the issue.sorry for trouble bro.
