### ISSUE TITLE
Please add xxxtube.desi

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#282]
Hi, as Vmasala and Porn HD cannot be fixed due to issue beyond our control, request you to remove these sites and add xxxdesi.tube. The site offers good Indian content

**Comment by JollyRog420** [comment]
Desi

**Comment by mrdougquaid** [comment]
Can you STOP submitting websites that do not even work?
Did you even look at the site before opening an issue here? 
Stop wasting our time with sites that don't even work.

**Comment by imurreflection** [comment]
Thank you so much Gujal00 bro.
