### ISSUE TITLE
VideoDevil Eporner not working

### ISSUE THREAD

**Issue by peanutBread** [xbmc-adult/xbmc-adult#287]
Since a few days Eporner is not working anymore.
I decided to look up why.

In the end they just switched the places of the src and id attribute of the thumbnail resulting in the regular expression not working anymore --> no video results.

To fix the issue edit plugin.video.videodevil\resources\eporner.com.cfg

and in Videos section change this
`item_infos=</div>\s+<a href="(/hd-porn/[^"]+)" title=" *([^"]+)".+?<img id="[^"]+" src="([^"]+)" .+?<div class="mbtim">*([^<]+)</div>`

to this
`item_infos=</div>\s+<a href="(/hd-porn/[^"]+)" title=" *([^"]+)".+?<img src="([^"]+)" id="[^"]+".+?<div class="mbtim">*([^<]+)</div>`

**Comment by mrdougquaid** [comment]
Fixed thanks
