### ISSUE TITLE
ero-erodouga.com problems

### ISSUE THREAD

**Issue by steph09** [xbmc-adult/xbmc-adult#29]
i notice that on the ero-erodouga.com part of the plugin the next button is no longer displaying & the categories option is also no longer there.

there is also issue that when you search it brings up a list of found items but once selected you are not able to play the video.

is it possible to fix?
i thank you for the hard work of keeping the plugin upto date & ensuring all works well.

**Comment by mrdougquaid** [comment]
This is a hard one to fix as it is in Japanese

**Comment by mrdougquaid** [comment]
Next button fixed

**Comment by mrdougquaid** [comment]
Removed it as it was unfixable
