### ISSUE TITLE
Please add javhihi.me

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#291]
Hi, please add this site back. It was earlier there in our add-on but was removed as it was not working. The site is back and is working flawlessly. This is one of the best uncensored Japanese site.

**Comment by imurreflection** [comment]
Just to let you know the other two Jav sites previously available in our add-on are also working flawlessly now. They are jav789.com and javbuz.com.

**Comment by imurreflection** [comment]
Hi gujal00 bro, is it possible to add these sites earlier present in our add-on. If its not, please advise and I will close this issue. The original issue was raised on 2nd may and I know that you are busy but its almost 2 months now. Sorry about asking for it again

**Comment by Gujal00** [comment]
The site uses a propreitary form of streaming which doesnt work with Kodi or VLC. Sorry can't be done as far as I can see
