### ISSUE TITLE
Please add xnxx.com

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#292]
Hi, as vmasala.com is not working for a long time now.May I request you to remove it and add xnxx.com one of the best Indian porn site.

**Comment by imurreflection** [comment]
Hi Mrdougquad and Gujal00 bro, I hope I m certainly wrong when I say this but have we stopped supporting our add-on. There have been issues pending from last month and there has been no response. This never happened earlier. If there is any issue due to which the issues cannot b addressed, please advise so that we should not trouble you further. This is the best Kodi add-on with extremely supportive developers and if you decide to abandon it, it will be an irony and great loss to community. Regards.

**Comment by tvaddonsco** [comment]
We will forward the suggestion to the addon's developer. Thank you!

**Comment by Gujal00** [comment]
desixnxx is for indian content and is already there is Videdevil
xnxx is a generic site and has loads of content (mostly 360p eventhough videos are marked 720p/1080p), though the organisation of the website is not ideal for scrpaing. Can be done, but not compelling enough

**Comment by imurreflection** [comment]
Thank you..no issues..
