### ISSUE TITLE
No NEXT page tab on search Analdin

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#296]
There is no ' Next' tab available when searching any keyword in the site Analdin.com. This limits the search to one page only. This happened earlier also but was resolved. Kindly fix it.

**Comment by Gujal00** [comment]
This has been answered before, the search result contains hundred results per page and it is not possible to build the next page url due to use of HTML5+CSS.
If the result is not in the first 100 matches, then one should use a better search term
