### ISSUE TITLE
data18 web content NfoUrl needs updating

### ISSUE THREAD

**Issue by cjd2004** [xbmc-adult/xbmc-adult#31]
data18 now use

http://www.data18.com/content/\d+
instead of 
http://www.data18.com/content/update_\d+.html

While the old url style works for some content (it redirects toto the new url), for others only the new url works.

**Comment by DoctorD1501** [comment]
Does this still need to be changed? I'm looking through the scraper code and I don't see anything about /update still in there.

**Comment by cjd2004** [comment]
Looks like this has been reverted on the Data18 side.

**Comment by cjd2004** [comment]
Works properly here now.
