### ISSUE TITLE
Please add desisexinthecity.org

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#310]
Amazing indian site with unseen and rare content. If possible, please add.

**Comment by Gujal00** [comment]
The site does not host any videos and is embedding videos from multiple hosters such as Xvideos, Pornhub and Redtube which are already included in Videodevil
Not worthwhile adding this consolidator site

**Comment by imurreflection** [comment]
Oh...sorry about that..closing the issue
