### ISSUE TITLE
Desixnxx.net

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#316]
It appears that this site domain name has been changed to desixnxx2.net as the main site desixnxx.net is not working anymore.

**Comment by mrdougquaid** [comment]
What do you mean by "is not working" ? 

desixnxx.net page loads fine for me

**Comment by imurreflection** [comment]
Not working means, the video does not play on any browser. The site and the video page loads though. On your addon, the site loads but video does not play. It's because they are now updating desixnxx2.net . If you see the videos listed on desixnxx.net are actually listed 5-6 pages later in desixnxx2.net. if on browser or in the addon, the site plays fine, let me know and i will close the issue mrdougquad.

**Comment by Gujal00** [comment]
desixnxx in VideoDevil is working fine in listing, pagination, search and playing videos (went upto 10 pages)
The Genre section is now empty as it is empty on the site itself
I dont see any issue

Can you provide a log on what issue you are facing?

**Comment by imurreflection** [comment]
Not sure what happened but at the time of reporting this issue, the site was completely not working in your addon but now it's working fine. Surprisingly, even javwhore is working fine which you said cannot b fixed due to kvs encryption. Some more sites like kissjav etc not working. However, please note that only desixnxx2 net is being updated daily. If possible, please look into the possibility of updating it. Thank you. Closing the issue now.
