### ISSUE TITLE
since 1.7.239 videodevil is not working anymore

### ISSUE THREAD

**Issue by Last-Dance-Official** [xbmc-adult/xbmc-adult#324]
`17:26:55.326 T:545143468256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib2to3.pgen2.parse
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.videodevil/default.py", line 21, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/plugin.video.videodevil/default.py", line 15, in __init__
                                                self.run()
                                              File "/storage/.kodi/addons/plugin.video.videodevil/default.py", line 18, in run
                                                import videodevil
                                              File "/storage/.kodi/addons/plugin.video.videodevil/videodevil.py", line 7, in <module>
                                                from past.builtins import basestring
                                              File "/storage/.kodi/addons/script.module.future/libs/past/__init__.py", line 88, in <module>
                                                from past.translation import install_hooks as autotranslate
                                              File "/storage/.kodi/addons/script.module.future/libs/past/translation/__init__.py", line 41, in <module>
                                                from lib2to3.pgen2.parse import ParseError
                                            ImportError: No module named lib2to3.pgen2.parse
                                            -->End of Python script error report<--
17:26:55.616 T:547892494336   ERROR: GetDirectory - Error getting plugin://plugin.video.videodevil/
17:26:55.617 T:547892494336   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videodevil/) failed`

**Comment by xalaros** [comment]
I agree, same problem with me (not opening on CoreELEC v9.2.1) since 1.7.239

**Comment by Gujal00** [comment]
Need full debug log, as snippets are no good for debugging as I can't even tell what version of kodi you are running on what platform.

My guess is you are running Open/Libre/Core Elec and yes they do not come with the requisite lib2to3 library and wont work on those platforms. They are trying to add this library through a PR only 2 days ago
https://github.com/LibreELEC/LibreELEC.tv/pull/4146

If not, Please upload the full debug log using the Kodi Log Uploader Program Addon found in Kodi repo and then provide the link it generates here.

**Comment by Last-Dance-Official** [comment]
Yes its LibreElec im using, and fixed it now by doing:

in file 
```
/storage/.kodi/addons/script.module.future/libs/past/translation/__init__.py
```
comment out lines 41 and 42:
```
#from lib2to3.pgen2.parse import ParseError
#from lib2to3.refactor import RefactoringTool
```

in file 
```
/storage/.kodi/addons/script.module.future/libs/libfuturize/fixes/__init__.py
```
comment out line 2:
```
#from lib2to3 import refactor
```

(thx to 0rphu)

**Comment by Gujal00** [comment]
@Last-Dance-Official @StockportJambo @xalaros 
Rather than editing the py files to remove references to lib2to3, It is actually advisable to install lib2to3
Get the zip file [from here](http://ge.tt/76kzUy03). you need lib2to3K18.zip for LE9.2 release version OR  lib2to3K19.zip for the nightly devel version by Milhouse based on Kodi19 depending on what release you are running
Upload the zip file to LE machine Downloads share and extract it as follows from ssh terminal
```
cd /storage/.kodi/addons/script.module.future/libs
unzip /storage/downloads/lib2to3K18.zip
```
Restart LE and Videodevil will work after that

**Comment by Sanjivsharma91** [comment]
It helped perfectly on Kodi Leia.
Thanks a ton!

**Comment by Spytman** [comment]
> @Last-Dance-Official @StockportJambo @xalaros
> Rather than editing the py files to remove references to lib2to3, It is actually advisable to install lib2to3
> Get the zip file [from here](http://ge.tt/76kzUy03). you need lib2to3K18.zip for LE9.2 release version OR lib2to3K19.zip for the nightly devel version by Milhouse based on Kodi19 depending on what release you are running
> Upload the zip file to LE machine Downloads share and extract it as follows from ssh terminal
> 
> ```
> cd /storage/.kodi/addons/script.module.future/libs
> unzip /storage/downloads/lib2to3K18.zip
> ```
> 
> Restart LE and Videodevil will work after that

Could anyone explain in steps how i can get this to work on a LibreELEC 9.2.0 On Raspberry 3?
I'm not a complete noob but i would appriciate a guide on how to do the steps properly. 
I miss my Videodevil ;)

**Comment by whatever2016** [comment]
Hi guys, even 1.7240 videoDevil not working, please see 2 attachments for log error info. Thanks.
![F91C6C7D-E069-4B1E-8E36-F7FCECE1DA1C](https://user-images.githubusercontent.com/16768072/74683882-40aa4180-5198-11ea-889c-0d155fc17aba.png)
![Uploading 27C76255-F2FD-489A-8D3C-F25AF18ED806.png…]()

**Comment by Gujal00** [comment]
> 
> 
> > @Last-Dance-Official @StockportJambo @xalaros
> > Rather than editing the py files to remove references to lib2to3, It is actually advisable to install lib2to3
> > Get the zip file [from here](http://ge.tt/76kzUy03). you need lib2to3K18.zip for LE9.2 release version OR lib2to3K19.zip for the nightly devel version by Milhouse based on Kodi19 depending on what release you are running
> > Upload the zip file to LE machine Downloads share and extract it as follows from ssh terminal
> > ```
> > cd /storage/.kodi/addons/script.module.future/libs
> > unzip /storage/downloads/lib2to3K18.zip
> > ```
> > 
> > 
> > Restart LE and Videodevil will work after that
> 
> Could anyone explain in steps how i can get this to work on a LibreELEC 9.2.0 On Raspberry 3?
> I'm not a complete noob but i would appriciate a guide on how to do the steps properly.
> I miss my Videodevil ;)

There are only 4 steps and all 4 are listed in my post, cant get anymore detailed than that

**Comment by Gujal00** [comment]
> Hi guys, even 1.7240 videoDevil not working, please see 2 attachments for log error info. Thanks.
> F91C6C7D-E069-4B1E-8E36-F7FCECE1DA1C
> Uploading 27C76255-F2FD-489A-8D3C-F25AF18ED806.png…

Screenshots are of no use, please upload full debug log using kodi log uploader and post the link here.
Anyway, every version from 1.7.239 onwards uses Future library for Python2/3 compatibility and will have issues on Libre/Core/OpenElec unless lib2to3 is present. Latest nightlies of LE have this library included

**Comment by Spytman** [comment]
> > > @Last-Dance-Official @StockportJambo @xalaros
> > > Rather than editing the py files to remove references to lib2to3, It is actually advisable to install lib2to3
> > > Get the zip file [from here](http://ge.tt/76kzUy03). you need lib2to3K18.zip for LE9.2 release version OR lib2to3K19.zip for the nightly devel version by Milhouse based on Kodi19 depending on what release you are running
> > > Upload the zip file to LE machine Downloads share and extract it as follows from ssh terminal
> > > ```
> > > cd /storage/.kodi/addons/script.module.future/libs
> > > unzip /storage/downloads/lib2to3K18.zip
> > > ```
> > > 
> > > 
> > > Restart LE and Videodevil will work after that
> > 
> > 
> > Could anyone explain in steps how i can get this to work on a LibreELEC 9.2.0 On Raspberry 3?
> > I'm not a complete noob but i would appriciate a guide on how to do the steps properly.
> > I miss my Videodevil ;)
> 
> There are only 4 steps and all 4 are listed in my post, cant get anymore detailed than that

Ok i'm sorry i asked. But my experience with SSH Terminals are limited. I do not know where LE machine Downloads share are so maybe it is just 4 steps but i still don't know how to do it.

**Comment by Sanjivsharma91** [comment]
> > > > @Last-Dance-Official @StockportJambo @xalaros
> > > > Rather than editing the py files to remove references to lib2to3, It is actually advisable to install lib2to3
> > > > Get the zip file [from here](http://ge.tt/76kzUy03). you need lib2to3K18.zip for LE9.2 release version OR lib2to3K19.zip for the nightly devel version by Milhouse based on Kodi19 depending on what release you are running
> > > > Upload the zip file to LE machine Downloads share and extract it as follows from ssh terminal
> > > > ```
> > > > cd /storage/.kodi/addons/script.module.future/libs
> > > > unzip /storage/downloads/lib2to3K18.zip
> > > > ```
> > > > 
> > > > 
> > > > Restart LE and Videodevil will work after that
> > > 
> > > 
> > > Could anyone explain in steps how i can get this to work on a LibreELEC 9.2.0 On Raspberry 3?
> > > I'm not a complete noob but i would appriciate a guide on how to do the steps properly.
> > > I miss my Videodevil ;)
> > 
> > 
> > There are only 4 steps and all 4 are listed in my post, cant get anymore detailed than that
> 
> Ok i'm sorry i asked. But my experience with SSH Terminals are limited. I do not know where LE machine Downloads share are so maybe it is just 4 steps but i still don't know how to do it.

You need to access your LibreELEC device folders either from Android phone or from PC ? (I did it from my Android phone)

You need to simply copy the folder extracted from the zip file as mentioned (in your case it is lib2to3K18.zip).  The folder name is lib2to3.  Once extracted on your PC or phone, you need to copy this folder into the location as mentioned i.e. to 

/storage/.kodi/addons/script.module.future/libs

Once copied, reboot the Kodi device and you are through.

![Capture2](https://user-images.githubusercontent.com/61022611/74735544-edf38700-5276-11ea-8d35-f3a1995ed56e.png)

Get back if still under confusion.

**Comment by whatever2016** [comment]
Hey guys, very interestingly, latest 1.7240 working on ALL Android boxes running Lea 18.4, however, for iOS Kodi, even Kypton 17.6 not working, even w/ or without VPN.

**Comment by Spytman** [comment]
> > > > > @Last-Dance-Official @StockportJambo @xalaros
> > > > > Rather than editing the py files to remove references to lib2to3, It is actually advisable to install lib2to3
> > > > > Get the zip file [from here](http://ge.tt/76kzUy03). you need lib2to3K18.zip for LE9.2 release version OR lib2to3K19.zip for the nightly devel version by Milhouse based on Kodi19 depending on what release you are running
> > > > > Upload the zip file to LE machine Downloads share and extract it as follows from ssh terminal
> > > > > ```
> > > > > cd /storage/.kodi/addons/script.module.future/libs
> > > > > unzip /storage/downloads/lib2to3K18.zip
> > > > > ```
> > > > > 
> > > > > 
> > > > > Restart LE and Videodevil will work after that
> > > > 
> > > > 
> > > > Could anyone explain in steps how i can get this to work on a LibreELEC 9.2.0 On Raspberry 3?
> > > > I'm not a complete noob but i would appriciate a guide on how to do the steps properly.
> > > > I miss my Videodevil ;)
> > > 
> > > 
> > > There are only 4 steps and all 4 are listed in my post, cant get anymore detailed than that
> > 
> > 
> > Ok i'm sorry i asked. But my experience with SSH Terminals are limited. I do not know where LE machine Downloads share are so maybe it is just 4 steps but i still don't know how to do it.
> 
> You need to access your LibreELEC device folders either from Android phone or from PC ? (I did it from my Android phone)
> 
> You need to simply copy the folder extracted from the zip file as mentioned (in your case it is lib2to3K18.zip). The folder name is lib2to3. Once extracted on your PC or phone, you need to copy this folder into the location as mentioned i.e. to
> 
> /storage/.kodi/addons/script.module.future/libs
> 
> Once copied, reboot the Kodi device and you are through.
> 
> ![Capture2](https://user-images.githubusercontent.com/61022611/74735544-edf38700-5276-11ea-8d35-f3a1995ed56e.png)
> 
> Get back if still under confusion.

Hi yes im sorry but i dont know how to get the file copied to the right folder. How do i access the files from PC? I have putty and can log on but i dont know how to get the file copied. I need a N00b guide ;) Thx
I tried to enter the IP address in windows explorer but that does not work.

**Comment by Sanjivsharma91** [comment]
Ok
Now you need to do a few things and leave putty aside.

1.  You have to download https://winscp.net/download/WinSCP-5.17-Setup.exe file from the relevant site and install this on your PC.

2.  Download the RELEVANT FILE (DEPENDING UPON YOUR KODI VERSION) from
 https://github.com/xbmc-adult/xbmc-adult/issues/324#issuecomment-579554840

Now unzip this file and extract the folder to the PC's DESKTOP.

3.  Now get your IP address, Username root's password from the Pi and open Winscp from the shortcut on Desktop on PC

4. ON the Login window of WinSCP Select File protocol as SFTP, input YOUR ip address in HOSTNAME, the port number 22, User name as root and put password in the box available.

5. Click Login and Winscp will connect to your device. 

YOU HAVE TWO WINDOWS HERE IN WINSCP

LEFT WINDOW IS YOUR LOCAL PC FOLDERS       AND      RIGHT WINDOW IS YOUR PI FOLDERS.

Browse to the path mentioned in the point 2 above in link i

/storage/.kodi/addons/script.module.future/libs on the RIGHT WINDOW OF WINSCP 

on the LEFT WINDOW OF THE WINSCP choose location Desktop and drag your folder in this location on Right window.

Reboot your Pi device and you are done.

**Comment by Spytman** [comment]
> Ok
> Now you need to do a few things and leave putty aside.
> 
> 1. You have to download https://winscp.net/download/WinSCP-5.17-Setup.exe file from the relevant site and install this on your PC.
> 2. Download the RELEVANT FILE (DEPENDING UPON YOUR KODI VERSION) from
>    [#324 (comment)](https://github.com/xbmc-adult/xbmc-adult/issues/324#issuecomment-579554840)
> 
> Now unzip this file and extract the folder to the PC's DESKTOP.
> 
> 1. Now get your IP address, Username root's password from the Pi and open Winscp from the shortcut on Desktop on PC
> 2. ON the Login window of WinSCP Select File protocol as SFTP, input YOUR ip address in HOSTNAME, the port number 22, User name as root and put password in the box available.
> 3. Click Login and Winscp will connect to your device.
> 
> YOU HAVE TWO WINDOWS HERE IN WINSCP
> 
> LEFT WINDOW IS YOUR LOCAL PC FOLDERS AND RIGHT WINDOW IS YOUR PI FOLDERS.
> 
> Browse to the path mentioned in the point 2 above in link i
> 
> /storage/.kodi/addons/script.module.future/libs on the RIGHT WINDOW OF WINSCP
> 
> on the LEFT WINDOW OF THE WINSCP choose location Desktop and drag your folder in this location on Right window.
> 
> Reboot your Pi device and you are done.

Thank you so much. Now i finally got it working. I'll buy you a beer if we ever meet. Thank you again!!

**Comment by Lamoboy** [comment]
None of the above methods will work on iOS platform. In this case, you should uninstall the latest version of the plugin and [install version 1.7.238](http://cdimage.debian.org/mirror/addons.superrepo.org/v7/addons/plugin.video.videodevil/plugin.video.videodevil-1.7.238.zip) and turn off automatic updates in the settings of the plugin.

**Comment by Gujal00** [comment]
@Lamoboy 

That is such a bad advice to give. Kodi 18.6 on iOS includes lib2to3 and should have no issues running latest VideoDevil. If not post a debug log

**Comment by Lamoboy** [comment]
Here is the debug log: https://mega.nz/#!lxUzBAKD!cmj75gyPXFJ2zJ_BtCVFZHUQ8BfusuaZunuBeQXm8zo

**Comment by Gujal00** [comment]
@Lamoboy Thanks for the debug log.
The problem seems to be specific to iOS as Future module is looking for a library
It is failing to find the library and errors.
`if sys.platform == 'darwin':
    from _scproxy import _get_proxy_settings, _get_proxies`
You can read this git below which talks about the missing modules in IOS and see if it works for you
https://github.com/pudquick/iPythonPatches

**Comment by Lamoboy** [comment]
The git that you pointed talks about missing modules not in iOS, but in some iPython app from App Store. There is no such app in the App Store right now, and even if it was, I don't think that it would help on a system level as all AppStore apps are sandboxed.

**Comment by Lamoboy** [comment]
Version 1.7.238 has stopped working on iOS. The latest version 1.7.242 is not even launching on iOS. Can you please integrate into the plugin all modules needed for iOS?

**Comment by mrdougquaid** [comment]
@Lamoboy  please provide logs if this is still happening and confirm which version of videodevil you are using

**Comment by Lamoboy** [comment]
The plugin has automatically updated to the latest version but it started to work only after the restart of the Kodi. You can close the issue.

**Comment by eGreyWolf** [comment]
Dear Colleagues!
Please give me a working link for **lib2to3K19**.zip (v. kodi-19.0-Matrix_beta2-x64)
Because [this one is](http://ge.tt/76kzUy03) broken here.

**Comment by Gujal00** [comment]
@eGreyWolf The addon is rewritten using six library, lib2to3 is not required anymore

**Comment by eGreyWolf** [comment]
Thank you, **@Gujal00**!
Do you mean «plugin.video.videodevil-1.7.237.zip»?
Kodi 19 (Matrix) has migrated to Python 3. And the «videodevil-1.7.237» plugin is not currently supported by this version of the KODI: Error "Not found XBMC.pyyton v. 2.14.0".
And... I naively believed that the tool you propose would be able to solve this problem.

**Comment by Gujal00** [comment]
@eGreyWolf Videodevil has been working fine on Matrix for over 6 months now. Why are You are using an ancient version of Videodevil. Install the xbmc-adult repo to get automatic updates. The current version of Videodevil as of 30-Dec-2020 is v1.8.9
