### ISSUE TITLE
Videodevil: pornHD not working

### ISSUE THREAD

**Issue by ghost** [xbmc-adult/xbmc-adult#326]
for a while now, pornhd does show the video overview but the videos will not start

**Comment by durangorob** [comment]
Videodevil been down for past few days.  Getting a python error when trying to open.   Is there a fix ?

**Comment by Gujal00** [comment]
@durangorob Please dont mix issues, raise a new one if you have to.
Most probably you re running a Libreelec variant and it is a known issue on that platform. Have a look at #324 for the temporary fix until Libreelec start including the lib2to3 library

**Comment by Gujal00** [comment]
@FrostyAmbulance8 
unfortunately PornHD can't be fixed as Videodevil lacks session cookies functionality which is required for videoplayback on this site
may be @mrdougquaid has a better idea

**Comment by mrdougquaid** [comment]
Not really, I would need a bit of time to understand how it works. Lets leave the issue open for the time being.

**Comment by antivirtel** [comment]
Looks like it's working now (works for me). Also they've introduced multiple pictures as a preview of the video (you can scroll your mouse on it). Can that be added to Kodi, like gif style, it would play the pictures with X second delay?
