### ISSUE TITLE
Videodevil download directory issue on iOS

### ISSUE THREAD

**Issue by Lamoboy** [xbmc-adult/xbmc-adult#333]
In order to be able to download videos after I set a directory in addon's settings, I should replace in file `\var\mobile\Library\Preferences\Kodi\userdata\addon_data\plugin.video.videodevil\settings.xml` this `special://envhome/` with that `/var/mobile/`.
Please fix this.

**Comment by Gujal00** [comment]
That is Kodi issue, special://envhome should be resolved by Kodi to the addon data folder automatically depending on the platform
