### ISSUE TITLE
xhamster plugin requires referer for video urls in plugin.video.videodevil

### ISSUE THREAD

**Issue by grocal** [xbmc-adult/xbmc-adult#341]
Steps:
- install plugin.video.videodevil
- go to xhamster section
- select video a and try to play it

Result: 
- doesn't play, error(22) / http error 403 shows up in logs upon video playing

Expected result:
- video plays

Tested with 1.7.240 on Android Box and Windows 10 PC.

Simple as that. Right now with current version it does not play xhamster.com videos and curl returns 403 http status. If I append manually `|Referer=xhamster.com` to video url for xhamster plugin - it works. Exactly as it is now done for tukif in `videodevil.py` file. But it's a crude and dirty solution. Unfortunately video files are not always recognizable via url if they are from xhamster (some other CDNs are used), so something more proper should be done like always forced referer appending for video urls.

Thanks in advance!

**Comment by mrdougquaid** [comment]
Fixed in 1.7.241
