### ISSUE TITLE
Videodevil 1.7.241 error pop-up in certain  submenu option

### ISSUE THREAD

**Issue by qoaa** [xbmc-adult/xbmc-adult#342]
I've tried searching and I've found this situation in random sites with no easy fixes found, just python programming tips to avoid said problem.

Anyway in a submenu for example in motherless then trying to open the groups submenus causes the error pop-up

> Videodevil Error
> Error running Videodevil
> 
> Reason:
> 'utf8' codec can't decode byte 0xfc in position 373825: invalid start byte

Hitting OK just returns to Motherless screen with every 'click' on Groups giving that pop-up error. 

It's possible it's my distro or my kodi version or combination of both cause I noticed this error in another addon, it's not really important issue and likely my issue as I don't know if others have seen similar error pop or not. It's also possible I may need to reformat/reinstall my media box, it's an core2quad desktop used as a media pc temporarily. 

System: x86_64 
OS: Libreelec 9.2.2 (x86_64 version) 
Kodi Leia 18.6 
Videodevil 1.7.241

**Comment by Gujal00** [comment]
@qoaa can you please check with Videodevil 1.8.x and report if the issue still exists. Thanks

**Comment by mrdougquaid** [comment]
Closing due to lack of response. Please re-open if this is still an issue
