### ISSUE TITLE
VideoDevil 1.7.246/247 won't start anymore

### ISSUE THREAD

**Issue by mdica** [xbmc-adult/xbmc-adult#363]
Directly after startup i got an error:
'ascii' codec can't encode character u'\xfc' in position 5: ordinal not in range(128)

**Comment by mdica** [comment]
If i change the language of kodi to english then it works. Maybe an error with the german translation

**Comment by Gujal00** [comment]
@mdica please provide full debug log, so that the offending code could be located, just a snippet is of no use.
Can you also try by disabling the disclaimer in Videodevil settings and then start videodevil

**Comment by mdica** [comment]
The start of VideoDevil begins at line 1100
[kodi.log](https://github.com/xbmc-adult/xbmc-adult/files/4941113/kodi.log)

**Comment by mdica** [comment]
When the disclaimer is turned off, VideoDevil starts.
