### ISSUE TITLE
Adultdvdempire scraper not working

### ISSUE THREAD

**Issue by poppytoppy** [xbmc-adult/xbmc-adult#39]
Unable to fetch data at all; "unable to connect to remote server" 

Version 1.0.9

**Comment by JeepFiend** [comment]
I can pull data fine, but it's not pulling box cover images on any of the movies updated on the site to have the boxcover .jpg replaced by a preview linked under the image.  Change went into effect a couple weeks ago.

version 1.0.9
Ubuntu 14.04

**Comment by selim29** [comment]
Nice

**Comment by cosmotic1** [comment]
I created a new version of the scraper... [metadata.movie.adultdvdempire.com-1.1.1~beta.zip](https://github.com/xbmc-adult/xbmc-adult/files/66635/metadata.movie.adultdvdempire.com-1.1.1.beta.zip).

**Comment by mrdougquaid** [comment]
Thanks fixed by committing the pull request
