### ISSUE TITLE
youjizz plugin - videos don't match thumbnails

### ISSUE THREAD

**Issue by vanomania** [xbmc-adult/xbmc-adult#4]
I did a little troubleshooting and noticed that the re used for matchurl is expecting only 1 url per video, but the main index actually has two hrefs per video, one on the whole 
thumbnail, and one on the title.  There's only one href per video on the search page though.  But I managed to fix it in my by prepending 

class="frame" href=\'

to the re.

**Comment by mrdougquaid** [comment]
Fixed 

thanks.
