### ISSUE TITLE
Videodevil doesn’t RECORD video on Pornhub

### ISSUE THREAD

**Issue by JNightshade** [xbmc-adult/xbmc-adult#415]
Hi,
I noticed VideoDevil 1.8.11  doesn’t record videos on Pornhub on Kodi 18.9 Leia. 
I updated to Kodi 19 Matrix and VideoDevil doesn’t load. 
Thanks. Much appreciated.

**Comment by JNightshade** [comment]
Am I the only one having this problem? Or is the “creator” just busy with life. 
I’m not even sure if this is the proper way to ask for help with it. It DOES record on other sites except for Pornhub. 

Thanks.

**Comment by ghost** [comment]
What do you mean by "doesn't record"? It cannot download videos?
And yes, this plugin is not actively maintained :(

**Comment by mrdougquaid** [comment]
We fix issues when we can

**Comment by JNightshade** [comment]
> We fix issues when we can

And we're very appreciative. I apologize if I didn't request or report properly. Should I stick with Leia 18.9? 
Does it work with Kodi 19?
Working fine today for me using Kodi 18.9. 

Thanks.

**Comment by JNightshade** [comment]
> What do you mean by "doesn't record"? It cannot download videos?
> And yes, this plugin is not actively maintained :(

You can choose to "record" a video in settings. It wasn't working in Pornhub, but then playback wasn't either. Seems good now.

**Comment by Gujal00** [comment]
@JNightshade please close the issue if it is resolved

**Comment by JNightshade** [comment]
> @JNightshade please close the issue if it is resolved

Sorry I’m having trouble seeing that option.
