### ISSUE TITLE
My Video Devil Is Not Working/How Do I Fix

### ISSUE THREAD

**Issue by sausagerocket** [xbmc-adult/xbmc-adult#416]
Hello my video devil is not working, seems like no matter what I do I get "Video Devil: Sorry Unable to find the video" seems like nothing works. What can I do to fix this my email is: rxpayne@gmail.com

**Comment by SyntaxxxErr0r** [comment]
I am also experiencing this issue with pornhub specifically... some videos work from motherless 

haven’t quite tried the other venues yet

**Comment by ghost** [comment]
Pornhub will be fixed very soon

**Comment by ghost** [comment]
> Hello my video devil is not working, seems like no matter what I do I get "Video Devil: Sorry Unable to find the video" seems like nothing works. What can I do to fix this my email is: [rxpayne@gmail.com](mailto:rxpayne@gmail.com)

On what website?

**Comment by sausagerocket** [comment]
Phone number changed.
