### ISSUE TITLE
Videodevil GirlfriendVideos "Next Page" on main screen doesn't work

### ISSUE THREAD

**Issue by vecnar** [xbmc-adult/xbmc-adult#424]
Hello,
Thank you for fixing issue [423](https://github.com/xbmc-adult/xbmc-adult/issues/423)! Didn't want to reply to say thank you and reopen the issue.

Kodi (18.4 Git:20190831-3ade758ceb). Platform: Windows NT x86 64-bit
plugin.video.videodevil v1.8.14 installed

Since version 18.4 "Next Page" on main screen doesn't work, same list of videos reloads. It works within "most viewed" and "top rated". Also no Categories listed, not sure if it was like that before or not but thought to mention.

`2021-07-29 01:35:15.704 T:20276   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.videodevil/?url=title%3a%20Next%20page%20%26cfg%3agfvideos.com.cfg%26director%3aVideoDevil%26genre%3aGirlfriendVideos%26type%3arss%26icon%3aC%3a%5cUsers%5coleg%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.videodevil%5cresources%5cimages%5cnext.png%26url%3ahttps%253A%252F%252F%252Fpages%252Findex%252F2.php
2021-07-29 01:35:15.712 T:196   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videodevil/?url=title%3a%20Next%20page%20%26cfg%3agfvideos.com.cfg%26director%3aVideoDevil%26genre%3aGirlfriendVideos%26type%3arss%26icon%3aC%3a%5cUsers%5coleg%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.videodevil%5cresources%5cimages%5cnext.png%26url%3ahttps%253A%252F%252F%252Fpages%252Findex%252F2.php) failed`

**Comment by vecnar** [comment]
Hello,
I replaced existing resources/gfvideos.com.cfg with the new one and next page button works, thank you! 
I mentioned missing categories in the same post and this is still an issue, should I create a new issue for categories?

**Comment by mrdougquaid** [comment]
Yes please
