### ISSUE TITLE
viedeodevil 1.8.19 update

### ISSUE THREAD

**Issue by demex2008** [xbmc-adult/xbmc-adult#437]
hallo the new Update ist Not Work 1.8.18 to 1.8.19 testet in Android anderen my Box.

**Comment by Gujal00** [comment]
@mrdougquaid 1.8.19 zip file not present in repo, it still has the 1.8.18.zip causing 404 error when trying to update

**Comment by mrdougquaid** [comment]
Fixed sorry for the blunder
