### ISSUE TITLE
Is videodevil down again?

### ISSUE THREAD

**Issue by cjtharris** [xbmc-adult/xbmc-adult#438]
I’m a REAL noob to all this stuff but the other day I notice videodevil was acting up. PornHub would give me a “Videodevil: Sorry! U able to find video”. So I installed ExpressVPN thinking it could be blocked by my internet provider but I still get that message. All of this is on my Firestick running 18.9, videodevil xbmc version 1.8.11

Any help is appreciated.

**Comment by Gujal00** [comment]
Can you check if pornhub is working on web browser?

**Comment by cjtharris** [comment]
I can play it on Android phone. I’ll check from my MacBook later today.

**Comment by cjtharris** [comment]
Yea I can view it on my laptops. So I guess that rules out if my ISP is blocking it.

**Comment by Gujal00** [comment]
okay gone through the code, unfortunately they are using JS obfuscation of the streamurls now. Videodevil catcher is pretty basic and cant handle obfuscation. So for now treat Pornhub as broken in Videodevil

**Comment by Gujal00** [comment]
@cjtharris pornhub fixed in Videodevil 1.8.20
please check and if working fine, close this issue

**Comment by cjtharris** [comment]
Will do

**Comment by cjtharris** [comment]
Will do
