### ISSUE TITLE
Empflix broken

### ISSUE THREAD

**Issue by mrgsi** [xbmc-adult/xbmc-adult#442]
I noticed Empflix is broken due to a change in empflix.com. I played with the categories link and changed it from /categories.php to just /categories and got those to display but no content since I didn't know what to change after that.

**Comment by Gujal00** [comment]
Is it inside Videodevil addon or Empflix addon?

**Comment by mrgsi** [comment]
Emplix Add-on doesn't work at all, just errors out. I went into the addon.py and changed "https://www.empflix.com/categories.php" to "https://www.empflix.com/categories" (to match the website URL) and it finally loaded the category menu but still no content. I don't know python so couldn't change anything else to get the rest of it working. I'm assuming the directory structure changed on emplix.com so the add-on broke.

**Comment by Gujal00** [comment]
> Emplix Add-on doesn't work at all, just errors out.

Why are you not using Empflix inside Videodevil, it has more functionality there as it supports sorting, filtering by duration, searching etc.

PR #444 raised containing both videodevil and empflix addon fixes for @mrdougquaid to review and approve

**Comment by Gujal00** [comment]
> Emplix Add-on doesn't work at all, just errors out. 

Why are you not using Empflix inside Videodevil, it has more functionality there as it supports sorting, filtering by duration, searching etc.
