### ISSUE TITLE
This is a feature request

### ISSUE THREAD

**Issue by ghost** [xbmc-adult/xbmc-adult#47]
hi
I've managed to modify VideoDevil code on my machine to add a fully working proxy support using urllib2.ProxyHandler.
the reason is that i only use proxy for this addon instead of forcing the whole system to use a proxy.
if it's enabled it will override the system default proxy and if disabled to will use the system proxy.

now, i don't know if i can add it here, or if anyone is interested.

also i've only tested it on Ubuntu and Openelec.

![dsc_0132](https://cloud.githubusercontent.com/assets/10340842/8368247/7d92425a-1bb0-11e5-831e-4ef122a4d572.JPG)

**Comment by mrdougquaid** [comment]
Kodi already has proxy support

http://kodi.wiki/view/Settings/System#Internet_access

Use that. Adding a proxy to an addon is unnecessary and just adds complexity.
