### ISSUE TITLE
xhamster videos not playing in videodevil

### ISSUE THREAD

**Issue by mikeybs** [xbmc-adult/xbmc-adult#48]
here is the debug log after clicking on a video in an attempt to play it

19:45:51 T:140479514388352   DEBUG: Keyboard: scancode: 0x74, sym: 0x0112, unicode: 0x0000, modifier: 0x0
19:45:51 T:140479514388352   DEBUG: OnKey: down (0xf081) pressed, action is Down
19:45:52 T:140479514388352   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x000d, modifier: 0x0
19:45:52 T:140479514388352   DEBUG: OnKey: return (0xf00d) pressed, action is Select
19:45:52 T:140479514388352   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.videodevil/?url=title.append%3a%20(15%3a28)%26title%3aamateur%20(15%3a28)%26cfg%3axhamster.com.cfg%26director%3aVideoDevil%26genre%3axHamster%26type%3avideo%26icon%3ahttp%3a%2f%2fut05.xhcdn.com%2ft%2f196%2f9_4951196.jpg%26url%3ahttp%253A%252F%252Fxhamster.com%252Fmovies%252F4951196%252Famateur.html.videodevil)
19:45:52 T:140479514388352   DEBUG:   ParentPath = [plugin://plugin.video.videodevil/?url=title%3axHamster%26director%3aVideoDevil%26genre%3axHamster%26type%3arss%26icon%3a%2fstorage%2f.xbmc%2faddons%2fplugin.video.videodevil%2fresources%2fimages%2fxhamster.png%26url%3axhamster.com.cfg]
19:45:52 T:140477558937344   DEBUG: StartScript - calling plugin VideoDevil('plugin://plugin.video.videodevil/','40','?url=title.append%3a%20(15%3a28)%26title%3aamateur%20(15%3a28)%26cfg%3axhamster.com.cfg%26director%3aVideoDevil%26genre%3axHamster%26type%3avideo%26icon%3ahttp%3a%2f%2fut05.xhcdn.com%2ft%2f196%2f9_4951196.jpg%26url%3ahttp%253A%252F%252Fxhamster.com%252Fmovies%252F4951196%252Famateur.html.videodevil')
19:45:52 T:140477558937344   DEBUG: WaitOnScriptResult - waiting on the VideoDevil (id=57) plugin...
19:45:52 T:140477550544640  NOTICE: Thread LanguageInvoker start, auto delete: false
19:45:52 T:140477550544640    INFO: initializing python engine.
19:45:52 T:140477550544640   DEBUG: CPythonInvoker(57, /storage/.xbmc/addons/plugin.video.videodevil/default.py): start processing
19:45:52 T:140477550544640  NOTICE: -->Python Interpreter Initialized<--
19:45:52 T:140477550544640   DEBUG: CPythonInvoker(57, /storage/.xbmc/addons/plugin.video.videodevil/default.py): the source file to load is "/storage/.xbmc/addons/plugin.video.videodevil/default.py"
19:45:52 T:140477550544640   DEBUG: CPythonInvoker(57, /storage/.xbmc/addons/plugin.video.videodevil/default.py): setting the Python path to /storage/.xbmc/addons/plugin.video.videodevil:/storage/.xbmc/addons/script.module.t0mm0.common/lib:/storage/.xbmc/addons/script.module.simplejson/lib:/storage/.xbmc/addons/script.module.b808common/lib:/storage/.xbmc/addons/script.module.xsqueezecommon/lib:/storage/.xbmc/addons/script.module.myconnpy/lib:/storage/.xbmc/addons/script.module.httplib2/lib:/storage/.xbmc/addons/script.module.addon.common/lib:/storage/.xbmc/addons/script.module.pyxbmct/lib:/storage/.xbmc/addons/script.module.beautifulsoup/lib:/usr/share/xbmc/addons/script.module.pil/lib:/storage/.xbmc/addons/script.common.plugin.cache/lib:/storage/.xbmc/addons/script.module.simple.downloader/lib:/storage/.xbmc/addons/script.module.requests/lib:/storage/.xbmc/addons/script.module.pytz/lib:/storage/.xbmc/addons/script.module.pyxbmctmanager/lib:/storage/.xbmc/addons/script.module.axel.downloader/lib:/storage/.xbmc/addons/script.module.urlresolver/lib:/storage/.xbmc/addons/script.module.mechanize/lib:/usr/share/xbmc/addons/xbmc.debug/:/storage/.xbmc/addons/script.module.parsedom/lib:/storage/.xbmc/addons/script.module.elementtree/lib:/storage/.xbmc/addons/script.module.metahandler/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/PIL:/usr/lib/python2.7/site-packages/gtk-2.0
19:45:52 T:140477550544640   DEBUG: CPythonInvoker(57, /storage/.xbmc/addons/plugin.video.videodevil/default.py): entering source directory /storage/.xbmc/addons/plugin.video.videodevil
19:45:52 T:140477550544640   DEBUG: CPythonInvoker(57, /storage/.xbmc/addons/plugin.video.videodevil/default.py): instantiating addon using automatically obtained id of "plugin.video.videodevil" dependent on version 2.1.0 of the xbmc.python api
19:45:52 T:140477550544640   DEBUG: LocalizeStrings: no strings.po file exist at /storage/.xbmc/addons/plugin.video.videodevil/resources/language/English, fallback to strings.xml
19:45:52 T:140479514388352   DEBUG: ------ Window Init (DialogBusy.xml) ------
19:45:52 T:140477550544640    INFO: CPythonInvoker(57, /storage/.xbmc/addons/plugin.video.videodevil/default.py): script successfully run
19:45:53 T:140477550544640    INFO: Python script stopped
19:45:53 T:140477550544640   DEBUG: Thread LanguageInvoker 140477550544640 terminating
19:45:53 T:140477558937344   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
19:45:53 T:140479514388352   ERROR: GetDirectory - Error getting plugin://plugin.video.videodevil/?url=title.append%3a%20(15%3a28)%26title%3aamateur%20(15%3a28)%26cfg%3axhamster.com.cfg%26director%3aVideoDevil%26genre%3axHamster%26type%3avideo%26icon%3ahttp%3a%2f%2fut05.xhcdn.com%2ft%2f196%2f9_4951196.jpg%26url%3ahttp%253A%252F%252Fxhamster.com%252Fmovies%252F4951196%252Famateur.html.videodevil
19:45:53 T:140479514388352   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.videodevil/?url=title.append%3a%20(15%3a28)%26title%3aamateur%20(15%3a28)%26cfg%3axhamster.com.cfg%26director%3aVideoDevil%26genre%3axHamster%26type%3avideo%26icon%3ahttp%3a%2f%2fut05.xhcdn.com%2ft%2f196%2f9_4951196.jpg%26url%3ahttp%253A%252F%252Fxhamster.com%252Fmovies%252F4951196%252Famateur.html.videodevil) failed
19:45:53 T:140479514388352   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.videodevil/?url=title%3axHamster%26director%3aVideoDevil%26genre%3axHamster%26type%3arss%26icon%3a%2fstorage%2f.xbmc%2faddons%2fplugin.video.videodevil%2fresources%2fimages%2fxhamster.png%26url%3axhamster.com.cfg)
19:45:53 T:140479514388352   DEBUG:   ParentPath = [plugin://plugin.video.videodevil/]
19:45:53 T:140479514388352   DEBUG: Loading items: 49, directory: plugin://plugin.video.videodevil/?url=title%3axHamster%26director%3aVideoDevil%26genre%3axHamster%26type%3arss%26icon%3a%2fstorage%2f.xbmc%2faddons%2fplugin.video.videodevil%2fresources%2fimages%2fxhamster.png%26url%3axhamster.com.cfg sort method: 0, ascending: false
19:45:53 T:140477550544640  NOTICE: Thread BackgroundLoader start, auto delete: false
19:45:53 T:140477550544640   DEBUG: Thread BackgroundLoader 140477550544640 terminating
19:45:53 T:140479514388352   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
19:46:10 T:140479514388352   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/ImageLib-x86_64-linux.so)
19:46:10 T:140479514388352   DEBUG: Unloading: ImageLib-x86_64-linux.so
19:46:12 T:140479514388352    INFO: CheckIdle - Closing session to http://ut08.xhcdn.com (easy=0x7fc36c173ec0, multi=0x7fc36c037b90)
19:46:13 T:140479514388352    INFO: CheckIdle - Closing session to http://ut05.xhcdn.com (easy=0x7fc36c201730, multi=0x7fc36c06f480)
19:46:22 T:140477567330048   DEBUG: Thread JobWorker 140477567330048 terminating (autodelete)
19:46:23 T:140477558937344   DEBUG: Thread JobWorker 140477558937344 terminating (autodelete)

**Comment by mrdougquaid** [comment]
Looks like it is working  now
