### ISSUE TITLE
Repo is not working

### ISSUE THREAD

**Issue by danukachathu** [xbmc-adult/xbmc-adult#5]
Page not found.

https://raw.github.com/xbmc-adult/xbmc-adult/ghmaster/repository.xbmc-adult/repository.xbmc-adult-1.0.1.zip

**Comment by HIGHWAY99** [comment]
<datadir zip="true">http://github.com/xbmc-adult/xbmc-adult/raw/ghmaster</datadir>
it's set to true for zip but yet the path is to the base folder where they have to uncompressed version at.  Need to make make a /zips/ or /repo/ folder or such and put it in that line in the repository's addon.xml.  then include a folder for each addon with it's addon.xml, changelog.txt, icon.png, fanart.jpg and the zips for each current version.

**Comment by mrdougquaid** [comment]
This was a bad push and has been fixed. The zip files were not generated which caused them to get deleted in commit 7efd029976f063d97573ddc116ec6c4f5431dc93
