### ISSUE TITLE
Videodevil not working on Jarvis build.

### ISSUE THREAD

**Issue by delinend** [xbmc-adult/xbmc-adult#54]
Is there a plan, to get Videodevil to work, on Jarvis (openElec 17.0) build, with the new Newclock5 player ? Thay are not using DVDplayer anymore, but the new VideoPlayer.

Best regards

**Comment by mrdougquaid** [comment]
Taken from http://forum.kodi.tv/showthread.php?tid=188733&pid=2147580#pid2147580

they no longer use DVDPlayer as the renderer, but the next incarnation called just VideoPlayer. That small change is what was causing VideoDevil to not be able to pay any videos. The VideoDevil add-on will have to be reprogrammed to call on the new renderer for playback going forward with Jarvis.

Can you change the player in the add-on settings?

The only available options in the settings are AUTO, DVDPlayer, and MPlayer. None of those work in Jarvis. Milhouse is building his versions based entirely on VideoPlayer. I asked if it would be possible to add in a DVDPlayer module of some sort, but he said this is a fundamental program built into Jarvis code and there is no way to change it when compiling. It's cool. Until the VideoDevil addon is updated to use VideoPlayer, I've just reverted to Isengard. Seems less buggy anyway.

**Comment by mrdougquaid** [comment]
Can you try https://github.com/xbmc-adult/xbmc-adult/blob/JarvisPlayer/plugin.video.videodevil/plugin.video.videodevil-1.7.123.zip go in the add-on settings and change the video player to the JarvisVideoPlayer and let me know if it fixes the issue?

**Comment by luckyknight79** [comment]
@mrdougquaid 
I copied the plugin update and I get 'module' object has no attribute 'PLAYER_CORE_AUTO'

**Comment by delinend** [comment]
I also still see the message "'module' object has no attribute 'PLAYER_CORE_AUTO'"

**Comment by mrdougquaid** [comment]
Thanks. I have updated the zip file. Could you try now with the extra fixes ?

**Comment by delinend** [comment]
Hmm.. I get "Failed to install add-on from zip file" :-(

**Comment by mrdougquaid** [comment]
I regenerated the file could you try again please?

**Comment by delinend** [comment]
Now install okay... but VideoDevil fail to start, and I can't enter the Config menu.

**Comment by mrdougquaid** [comment]
Try this one please:

https://github.com/xbmc-adult/xbmc-adult/blob/JarvisPlayer/plugin.video.videodevil/plugin.video.videodevil-1.7.125.zip

**Comment by luckyknight79** [comment]
@mrdougquaid That works, thanks!

**Comment by mrdougquaid** [comment]
@luckyknight79 thanks. I will push it then as it does not break Gotham

**Comment by delinend** [comment]
Yes. Now it works. Thanks for your help.
