### ISSUE TITLE
AEBN Gay not scraping

### ISSUE THREAD

**Issue by hawkeyefla** [xbmc-adult/xbmc-adult#58]
The AEBN gay scraper (And I would imagine the non-gay as well) are not scraping right now.  A little research makes me thing that AEBN might have changed how their search URL works, but I'm not savvy enough with XML to really debug it.

**Comment by Tealhawke** [comment]
I have seen this too.. Reallu sucks

**Comment by tstop** [comment]
Is there any chance this might be fixed?

**Comment by mrdougquaid** [comment]
Nope not unless someone sends in a fix

**Comment by MegaS0ra** [comment]
I have fixed this and made a pull request  #128

**Comment by mrdougquaid** [comment]
Is this working now?
