### ISSUE TITLE
Unquoting plus signs

### ISSUE THREAD

**Issue by joedev1981** [xbmc-adult/xbmc-adult#68]
URLs encoded with plus signs are unquoted twice using urllib.unquote_plus (lines 869 and 912) in videodevil.py.

This prevents the "next page"  for searches with a space from working properly. Example:
 url = http%3A%2F%2Fwww.youporn.com%2Fsearch%2Frelevance%2F%3Fquery%3Dredhead%2Boutside%26page%3D2
 is passed to loadRemote.
Line 869 applies  urllib.unquote_plus
url = http://www.youporn.com/search/relevance/?query=redhead+outside&page=2

Line 912 applies  urllib.unquote_plus
http://www.youporn.com/search/relevance/?query=redhead outside&page=2

This results in a http error 400: bad request. Changing line 912 to urllib.unquote instead of urllib.unquote_plus fixes this problem but would break the search function. 

The problem seems to stem from the way the search input is handled. getKeyboard returns a string that has already undergone urllib.quote_plus in line 507 (spaces are converted to plus signs). Line 897 unnecessarily applies urllib.quote_plus again(plus signs are converted to %2B). Line 912 applies urllib.unquote_plus to convert %2B back to plus signs.

If we remove one of the urllib.quote_plus (from line 507 or 897) and change line 912 to urllib.unquote instead of urllib.unquote_plus allows the search function to work as usual and correctly handles urls passed to loadRemote that contain plus signs(or %2Bs)

This is a complex issue. Any thoughts on how this is best handled? I feel less is better and give the user more control (add more formatting options to the site configs).

**Comment by Gujal00** [comment]
@mrdougquaid This issue can now be closed
