### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by ghost** [xbmc-adult/xbmc-adult#7]
Are these plugins and this repository free to edit and share? I cannot find licencing information anywhere.

http://choosealicense.com/

**Comment by ToobsAU** [comment]
These addons were provided by many different developers... Many of whom are no longer actively involved with this repo. 

As such it would be unreasonable to distribute these under a single license without the input of the original developers, especially if the license permitted commercial / for profit use.

**Comment by beefcurtains** [comment]
Are the repository files redistributable?
