### ISSUE TITLE
Search dialog box popping up at random.

### ISSUE THREAD

**Issue by LucidEye** [xbmc-adult/xbmc-adult#78]
When using the search dialog box in Video Devil, once it has been opened, it keeps opening at random without user intervention.  It even opens while a video is playing.  This pretty much has rendered this whole addon unusable as the dialog box just keeps opening every few seconds and needs to manually be closed.  Once closed, the video that is playing stops and you get returned to the search results listing... where the search dialog box continues to open randomly.   This just started happening about a month or 2 ago after an update.
Also, keep getting timeout and other errors when trying to play videos.... the same videos play just fine on my laptop using a web browser... but the videos keep timing out in Video Devil.

**Comment by mrdougquaid** [comment]
Can't reproduce this

**Comment by LucidEye** [comment]
Well that's interesting since I have reproduced it without even trying on 4 separate Raspberry Pis... 

2 Model 2 quad-cores both running OpenELEC KODI 15.2 and VideoDevil 1.7.107 - once search dialog box is opened and used in VideoDevil, it will continue to re-open all by itself at random. This only happens in VideoDevil, no other addons exhibit this problem.

1 Model 2 quad-core running OpenELEC KODI 15.2 and VideoDevil 1.7.116 - once search dialog box is opened and used in VideoDevil, it will continue to re-open all by itself at random.  This only happens in VideoDevil, no other addons exhibit this problem.

1 Model 3 quad-core running KODI 15.2 as an app from a Raspbian desktop and VideoDevil  1.7.107 - once search dialog box is opened and used in VideoDevil, it will continue to re-open all by itself at random.  This only happens in VideoDevil, no other addons exhibit this problem.

All of these addons were installed from Super Repo or Fusion repositories. 

I just recently installed LibreELEC KODI 16.1 and VideoDevil 1.7.142 on a new Model 3 Pi and have not seen this behavior... yet.

I guess the question should be... why is the 'update' button grayed-out in the addon configuration settings on VideoDevil 1.7.107 and 1.7.116 versions?  Are we supposed to manually uninstall and update this addon when new versions are released?  I was under the impression that VideoDevil was supposed to automatically update when that option is turned on in the settings.  Can you please confirm this?

Guess I'll be manually upgrading all of my Pis to LibreELEC with KODI 16.1 and the latest addon versions.  So far, LibreELEC seems to be less buggy and much more stable than OpenELEC.

---

On Wed, 10/26/16, mrdougquaid notifications@github.com wrote:

 Subject: Re: [xbmc-adult/xbmc-adult] Search dialog box popping up at random. (#78)
 To: "xbmc-adult/xbmc-adult" xbmc-adult@noreply.github.com
 Cc: "LucidEye" jc_lafleur@yahoo.com, "Author" author@noreply.github.com
 Date: Wednesday, October 26, 2016, 5:13 AM

 Can't reproduce this

 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mrdougquaid** [comment]
1.7.107  was released 29 May 2015
1.7.116 was released 1 Sep 2015
Both over a year ago... 
Latest version is 1.7.143 released this week.

Add-ons usually auto-update and check for updates every day, not sure why the button is grayed out.
Superrepo and Fusion are not official repositories so if you are having issues with their updates you should take it up with them.
The official repo for videodevil is linked from [here](http://forum.kodi.tv/showthread.php?tid=188733&pid=1648712#pid1648712)

As for the dialog box issues I am unable to help there as I cannot reproduce the issue with the details you have provided. All I can suggest is to start from scratch, clean install, clean home directory etc
