### ISSUE TITLE
Changes in github breaks repository 

### ISSUE THREAD

**Issue by currently-off-my-rocker** [xbmc-adult/xbmc-adult#9]
Seems there is an issue with raw downloads that started late in March.
http://forum.xbmc.org/showthread.php?tid=189722 and others.
When adding repo it just ends up being empty. Log file has curl error 35. 

Other repos have changed the urls. I tried the same changes in this addon.xml and it seem to have worked. 

```
<info compressed="false">http://raw.github.com/xbmc-adult/xbmc-adult/ghmaster/addons.xml</info>
<checksum>http://raw.github.com/xbmc-adult/xbmc-adult/ghmaster/addons.xml.md5</checksum>
<datadir zip="true">http://raw.github.com/xbmc-adult/xbmc-adult/ghmaster/</datadir>
```

**Comment by mrdougquaid** [comment]
Fixed
