### ISSUE TITLE
xhampster  categories listing is broken

### ISSUE THREAD

**Issue by bobmcck** [xbmc-adult/xbmc-adult#91]
xhampster categories listing is broken.

Here is the fix.

In the file "xhamster.com.categories.cfg" replace the "item_infos" value with the following:

<a href="([^"]+)".+?class="hRotator"><img src='([^']+)' .+?alt=" *([^"]+)"/>.+?<b>([:\d]+)

**Comment by mrdougquaid** [comment]
Thanks!
