### ISSUE TITLE
Could one side be added?

### ISSUE THREAD

**Issue by Vilinius** [xbmc-adult/xbmc-adult#95]
Would you consider adding youspank to the list of the supported portals in vdeodevil?

**Comment by mrdougquaid** [comment]
Sorry no time to add extra sites, it is a lot of work already to keep existing sites running

**Comment by Vilinius** [comment]
Is there anywhere a tutorial for writing new plugins. Maybe I would be able to contribiute myself?
Regards

Vilinius

**Comment by mrdougquaid** [comment]
Nope this is all custom stuff. You can look at https://github.com/xbmc-adult/xbmc-adult/commit/04fef4c6e4ad601ad79fd77890be670362969a29 for the list of changes that are required to add a site. Along with https://docs.python.org/2/library/re.html you can probably come up with how to add a new site.

**Comment by Vashiel** [comment]
Well, i could help Vilinius, but i don't know the url of  this youspank site...soo

**Comment by Vilinius** [comment]
The site is not youspank, as I erroneous wrote but spankingtube.com

Sorry

**Comment by Vilinius** [comment]
Dear mrdougquaid, thanks for the hints.
Dear Vashiel, many thanks for your offer to help.

As I wrote, I do not understand the mechanics behind the code. However I made a part of the work - found the regular expressions.

LINK, TITLE, DURATION can be obtained with this RE:
'<a href="(/video/[^"]+)">.+?src="([^"]+)".+?class="duration">\s+([\d:]+).+?title-truncate[^">]+">([^<]+?)<'

SEARCH is simply the following call
 .... /search?search_query=XXX&search_type=videos



XXX is a string like milf, teen, girl.....

nice girl becomes
  .... /search?search_query=nice+girl&search_type=videos



NEXT
'<li><a href="([^"]+)" class="prevnext">'

CATEGORIES

'<div class="[^">]+">\s+<a href="([^">]+)">\s+<div class="[^>]+>\s+<[^>]+>\s+<div class[^>]+>\s+([^<]+?)\s+</div>'

eg.
('http://www.spankingtube.com/videos?c=22', 'Whipping')

I hope my work is useful.
If I understand more, maybe I would be able to maintain the other sites....

Regards

**Comment by Vilinius** [comment]
Vashiel, many thanks for the code.

Regards
